### ISSUE TITLE
Use AP11ROPE scans to comment-proof Luminary 99

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#1042]
Also look for any potential comment-text changes between the two.

**Comment by thewonderidiot** [comment]
As noted in #1041, we know of one comment change between the two: in the TABLE OF LOG SECTIONS in ASSEMBLY AND OPERATION INFORMATION, AP11ROPE retains the Luminary Revision 99 log section title of 
```
LEMONAID
```

instead of replacing it with

```
LNYAIDE
```

as was done in 99R1.

**Comment by rburkey2005** [comment]
Proofing comment text with octopus/ProoferComments.py completed through p. 106 so far.  Corrected a couple of typos in Luminary 99 and 69, but no real discrepancies between AP11ROPE and Luminary 99 yet, other than the one already noted.

**Comment by rburkey2005** [comment]
Completed pp. 107-215.  No additional typos in Luminary 99 or discrepancies between Luminary 99 and AP11ROPE discovered in that range.

**Comment by rburkey2005** [comment]
Completed pp. 216-325.  Fixed a typo or two in Luminary 69-131, but no new discrepancies between Luminary 99 and AP11ROPE were found.

**Comment by rburkey2005** [comment]
Completed pp. 326-560.  No new typos, no new mismatches between Luminary 99 and AP11ROPE.

**Comment by rburkey2005** [comment]
Completed pp. 561-1135. No new mismatches between Luminary 99 and AP11ROPE, but one typo found, and propagated to other Luminary versions as appropriate.

**Comment by rburkey2005** [comment]
Finished the complete proofing of Luminary 99 source vs AP11ROPE scans, using octopus/ProoferComments.py.

In total, there were 5-6 typos found in Luminary 99 source-code comments, which were fixed, and the fixes were propagated to other Luminary versions as needed.

The sole discrepancy found in the comments, between Luminary 99 source and AP11ROPE scans, was on page 2, ASSEMBLY AND OPERATION INFORMATION, and was the word "LNYAIDE" in Luminary 99 R1, but  "LEMONAID" in AP11ROPE.
