### ISSUE TITLE
VirtualAGC Simulation Manager no longer fits on screen - can't click Run!

### ISSUE THREAD

**Issue by retrac0** [virtualagc/virtualagc#1051]
Hi, I just pulled and built from GitHub (revision aa6c7390f517b2d53890b6553bd5f61b6f46447a) and it seems the number of possible simulation types now forces the Run! and other buttons off the screen, even at a fairly high resolution (2560 x 1080 in this case).  Screenshot attached.

![screenshot](https://user-images.githubusercontent.com/9069931/31108530-e0e1772c-a7c7-11e7-8077-11aab9fe3721.jpg)

There are various UI hacks to work around this (moving a window off the top of the screen for example) but it seems like a usability issue.

**Comment by rburkey2005** [comment]
@retrac0 Oops!  The UI actually modifies itself when it finds itself on a "small" display, but I failed to recognize that 1080 is "small".  (The UI is only 932 pixels high on my computer, so I guess I fooled myself that 1080 was plenty on everyone's computer.)  At any rate, I've changed it treat anything less than 1200 pixels of available height as "small", so it should automatically select the small UI and it should work for you now.  Hopefully.  There's a certain amount of trial-and-error involved, unfortunately.

I'll close this issue, tentatively, but do let me know if it doesn't work and needs to be reopened.

What you'll find in the "small" version of the UI is that the list of missions at the left side is instead changed to a drop-down list.  The downside is that you'll no longer have the "Custom" for running your own personalized AGC programs directly from the UI, but that's something I expect hardly anyone has ever done anyway.
