### ISSUE TITLE
Improve yaAGC debugger :)

### ISSUE THREAD

**Issue by Thymo-** [virtualagc/virtualagc#1056]
Could someone take a look at the debugger when there is some time to spare?

I often use it when debugging some stuff I wrote and it would be really helpful if I at least could get an octal display of values instead of hexadecimal and decimal. Maybe also binary display for the I/O channels?

Also I think not all help commands are up to date. E.g. when I do 'help obscure' I just get the default help text.

Lastly it would be really really beneficial if you can use the arrow keys to navigate command history or a way to easily step through a program using a hotkey. It's not very fun to debug large sections if you need to repeat step<CR> constantly.  My hands will love you. :smiley:

**Comment by ohommes** [comment]
Thymo,

You can already display things in octal, hex and decimal and also use the
original FMT specifiers (see NOUN SCALES AND FORMATS in the source code) to
have SP and  DP floats displayed like they are in the DSKY.

have you tried help for print? See the examples.  Once you use a format it
will keep that format.

/r

Onno

(agc) help print

Print the value of symbol EXP.

EXP can be a symbol (e.g. MPAC or &MPAC) or a dereferenced ADDRESS.

ADDRESS can be a pseudo linear address (e.g. 0x6c or 0154) or you can

use the AGC native address format and speficy the bank and octal value.


EXP may be preceded with /FMT, where FMT is a format letter

but no count or size letter (see "x" command). Without the

format letter, the default is octal.


Format letters are the usual

(o)ctal, he(x)adecimal, (d)ecimal, (u)nsigned, (t)wo base (i.e. binary)

and (f)loat. When decimal is selected yaAGC will use ones complement

implementation.


The AGC uses both Single Precision (SP) and (DP) instructions.

To specify how to print the float number an extension is added to

the FMT field to select the printing style. The printing style can be any

of the "NOUN SCALES AND FORMATS" (e.g. K for time in 1/100 of a sec).

In addition there is SP and DP for general single and double precision

printing. To use the extension use "print/f:<scalar_type>


Examples of EXP with or without formatting:

  print/d MPAC

  print/x &MPAC

  print *0x6c

  print *0154

  print *E0,1554

  print/f:K TIME2

**Comment by ohommes** [comment]
Here is an example of the printing of the TIME as you would see it in the
DSKY in seconds. I did a CTRL-C after 4.23 seconds

./yaAGC ../Colossus249/Colossus249.bin

Apollo Guidance Computer simulation, ver. 2017-06-19, built Jan  2 2018
14:01:52

Copyright (C) 2003-2009 Ronald S. Burkey, Onno Hommes.

yaAGC is free software, covered by the GNU General Public License, and you
are

welcome to change it and/or distribute copies of it under certain
conditions.

Refer to http://www.ibiblio.org/apollo/index.html for additional
information.

(agc) cont

[New Thread 11]

[Switching to Thread 11]

^CPOSTJUMP () at INTER-BANK_COMMUNICATION.agc:78

78 CA 0

(agc) print/f:K TIME2

$1 = 4.230000000

(agc)

**Comment by ohommes** [comment]
And to display a binary view of an IO Channel:

print /t CDUX

$1 = 000 000 000 000 000

**Comment by Thymo-** [comment]
That's really useful! Thanks!
I have really been relying on the things available through the 'info $thing' commands a little too much if I'm honest.
I hadn't realized you can display it this way. Suppose I should RTFM some more. :sweat_smile:

Thanks a lot!
