### ISSUE TITLE
Aurora 12 Work

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#107]
If you'd like us to pick an assignment for you, either leave a comment here, or email myself (thewonderidiot@gmail.com) or Ron Burkey (info@sandroid.com).

**Comment by rburkey2005** [comment]
How could this be closed, when there are still Aurora transcriptions issues open?

**Comment by thewonderidiot** [comment]
The original idea for this was that it would be a place for somebody who didn't want to pick their own thing to get an assignment. That never happened, and everything outside of Steve's sections and proofing is closed, so I didn't see a need for it anymore.

**Comment by rburkey2005** [comment]
Sorry, I fancied it was some kind of a milestone to indicate that the "Aurora work" was completed, and it didn't occur to me to double-check that notion.
