### ISSUE TITLE
Reconstruct LM131 Revision 1

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#1085]
### Branch
[lm131r1](https://github.com/virtualagc/virtualagc/tree/lm131r1)

### Changed Bugger Words from Closest Program (Luminary 131)
```
Bugger word mismatch in bank 31; actual 66356 != expected 57354 (diff = 07002)
Bugger word mismatch in bank 32; actual 61555 != expected 70253 (diff = 06476)
Bugger word mismatch in bank 33; actual 65026 != expected 61571 (diff = 03235)
Bugger word mismatch in bank 34; actual 72333 != expected 04157 (diff = 66154)
```

### Known Differences
- Implementation of Automatic P66
- Exact changes are almost exactly described by Luminary memo 143 (see below).

### Resources
- [Luminary 131 listing](https://archive.org/details/luminary131agcpr00miti)
- [Programmed Guidance Equations for Luminary 1C](http://www.ibiblio.org/apollo/Documents/j2-80-MSC-70-FS-2_text.pdf) - Norton document for LUM131A Rev 3 (which is very closely related to this version). Gives pseudocode implementation details.
- [Luminary Memo 143 - Automatic P66](http://www.ibiblio.org/apollo/Documents/LUM143_text.pdf) - Describes all changes between Luminary 131 and LM131 Revision 1.
- [Luminary Memo 148 - Call It LUMINARY 1D](http://www.ibiblio.org/apollo/Documents/LUM148_text.pdf) - Gives the number of words remaining in every bank of LM131 Revision 1. This lets us know exactly how many words were in each bank, and lets us know where to put the new P66 code.
- Luminary 1C flowcharts - TBD.

### Notes
I don't know how LM131 Rev 1 differs from LUM131A Rev 3 as described in the Norton book. They may be identical.

**Comment by rburkey2005** [comment]
I've updated the website and the VirtualAGC GUI, so I'd say this is done!  Great work as usual.
