### ISSUE TITLE
Reconstruct Artemis 071

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#1087]
### Branch
[artemis071](https://github.com/virtualagc/virtualagc/tree/artemis071)

### Changed Bugger Words from Closest Program (Artemis 072)
```
Bugger word mismatch in bank 01; actual 67773 != expected 67772 (diff = 00001)
Bugger word mismatch in bank 33; actual 32430 != expected 71641 (diff = 37211)
Bugger word mismatch in bank 34; actual 45775 != expected 45777 (diff = 00002)
```

### Known Differences
- None (but see notes for analysis of change asterisks).

### Resources
- [Artemis 072 listing](https://archive.org/details/Artemis072J2k60)

### Notes
The only tool we have to go by on this one is the change asterisks present in Artemis 072. Luckily, they seem like they're going to be quite useful.

The subroutine calls table contains a single asterisk, for the subroutine MENELAUS, which means that only that subroutine changed. Presumably, in Artemis 071, MENELAUS was revision 060 instead of 061:
![image](https://user-images.githubusercontent.com/94056/63076012-7cfa9d80-bee8-11e9-8c27-a12f34b81f64.png)

Looking through MENELAUS, there's only one small set of asterisks in the S-IVB shutdown logic:
![image](https://user-images.githubusercontent.com/94056/63076187-36f20980-bee9-11e9-99e0-273d35aedf2c.png)

There only appear to be asterisks in bank 33, which means one of two things: either (a) code was only deleted from banks 1 and 34 or (b) code was inserted or deleted in bank 33 as part of these asterisks, which changed offsets and therefore references in banks 1 and 34. Occam's razor suggests that the second option is more likely.

**Comment by thewonderidiot** [comment]
Okay, I think I've got this one cracked. I have a build that matches the Artemis 071 buggers completely, changing only the lines modified in the image above. There's a few steps of reasoning, but I think it all makes sense. The thinking is as follows:

1. The bugger words in banks 1 and 34 become correct if a single word is deleted from bank 33. Since the line `TCR DPAGREE` has an asterisk _and_ is the only line with a five-digit punch card number, I think it makes sense that this line was added, and was not present in Artemis 071. So, let's make the assumption that these changes were to correct a bug -- the occasional lack of sign-agreement in the DT calculation. Sign agreement bugs were relatively common throughout the program, so this seems like a reasonable assumption.

2. All but one of the remaining changed lines reference `MPAC`. `DPAGREE` assumes that the input is in MPAC. If the `TCR DPAGREE` was not present originally, then there's no need for the calculated DT to have been in `MPAC`. So it's quite likely that it was instead stored somewhere else.
The problem is, where was the number originally stored?

3. The logic following the `TCR DPAGREE` checks to see if the result is <= 0 (checking only the lower half of the result, from `MPAC +1`, which is why sign agreement really matters). If it is, it sets `AVEGDT +1` to 1. Otherwise, it stores `MPAC +1` right into `AVEGDT +1`. Considering that the comments discuss calculation of something called DT, and the ensuing code looks at `AVEGDT`, it seems safe to assume that `AVEGDT` was the location originally used instead of `MPAC`. So, in other words, every reference in this chunk of code to `MPAC` would have been `AVEGDT` in Artemis 071. As said above, this accounts for all but one of the change asterisks.

4. The final asterisk is on the line `TCF +2`. This one confused me for a bit, but now it makes perfect sense. This line forces `AVEGDT +1` to be set to `MPAC +1` in the case of a <=0 result. But since we've made the assumption that our calculated DT is _already_ in `AVEGDT` in Artemis 071, there's no need to do this. The `TCF +2` can instead be `TCF +3`, to go directly to the `TC TWIDDLE`.

With these changes all made, the bugger words exactly match the drawing. So in summary the changes are:
1. Delete the line `TCR DPAGREE`.
2. Change all references to `MPAC` to `AVEGDT`.
3. Change `TCF +2` to `TCF +3`.

**Comment by thewonderidiot** [comment]
The reconstructed code looks like this:
```
KILLSIVB EXIT
         INHINT
         EXTEND
         DCA    TIG
         DXCH   AVEGDT
         EXTEND
         DCS    TIME2
         DAS    AVEGDT
         CAE    AVEGDT +1

         EXTEND
         BZMF   +2
         TCF    +3
         CAF    ONE
         TS     AVEGDT +1
         TC     TWIDDLE
         ...
```
```

**Comment by rburkey2005** [comment]
@thewonderidiot I think this relates to PCR-320, "TLI Initiate/Cutoff Program", which was implemented in ARTEMIS 60 (COLOSSUS Memo #292), with some apparent cleanup of collateral damage in ARTEMIS 61 and 65 (COLOSSUS Memos 296 and 301).  The ARTEMIS 72 change would appear to be a 3rd cleanup.  Does that sound right?

**Comment by thewonderidiot** [comment]
Yeah, that sounds about right. I'd also swear up and down that I saw either a description of this anomaly, or the actual anomaly report, very recently.... but I cannot for the life of me remember where. It essentially confirmed my musings above about precision being the issue. Maybe it was in the Artemis binder at the MIT Museum and I failed to photograph it? If I remember correctly, it was anomaly ART-4.

**Comment by rburkey2005** [comment]
Don't know.  Unless I'm very much mistaken, I've never seen an ART-_x_ anomaly report.  I've merely seen references to them in COLOSSUS Memos.  Similarly, the COLOSSUS Memos mention a bunch of ACB-_x_ (presumably ACB Requests), and I've never seen any of those either.
