### ISSUE TITLE
Virtual AGC crashes when AGC CPU Bus Input/Output Monitor and/or  its subcomponents are started on Raspbian Buster

### ISSUE THREAD

**Issue by sachatholl** [virtualagc/virtualagc#1104]
Hi everyone,
I am running Virtual AGC on a rapberry pi 3 using Raspbian Buster with desktop and recommended software. Version : September 2019; Release date:2019-09-26 ; Kernel version:4.19 ; Size:2541 MB

I appologize, I am a super rooky in linux stuff, so I explain the best I can.

**In novice mode**, without using _AGC CPU BUS Input/Output and its subcomponents_, the Simulation status window, _yaDSKY2, yaDEDA, ya Telemetry and yaACA2_, **seem to work satisfying.**

**But after** selecting the simulation type "Apollo 11 Lunar Module" in "Expert Mode", which selects all _AGC CPU BUS Input/Output and its subcomponents_, The Simulation status window, _yaDSKY2, yaDEDA, ya Telemetry and yaACA2_ start, **but as soon as _yaTelemetry_ shows its first telemetry data coming in, every windows closes and the** VirtualAGC Simulation Manager pops up again.

The same happens if I select _AGC CPU BUS/INPUT/OUTPUT Monitor_ and no or all or some or only one of its subcomponents.

**If I deselect** the _AGC CPU BUS/INPUT/OUTPUT Monitor_ completely again. In this case **all the other components seem to work correctly** and I can enter verbs and nouns and get plausible looking responses from the DSKY2.

**What can I do to get the _AGC CPU BUS/INPUT/OUTPUT Monitor and its subcomponents_ run and working?**

**Here I explain my instalation process so far on the raspberry pi 3 operated on Rapbian Buster:**

1) I downloaded vAGC  and decompressed it  using the link: 
 `https://www.ibiblio.org/apollo/Downloads/VirtualAGC-Raspbian-2017-08-31.tar.xz
`
Of course I was not able to get it started succesfully, so I decided to read more...

2) Then I applied without succes: 
s`udo apt-get install wx2.8-headers libwxgtk2.8-0 libwxgtk2.8-dev libsdl-dev libncurses5-dev liballegro4-dev git`

all the 2.8 components were not downloadable,

3)but managed to clone
`git clone --depth 1 https://github.com/virtualagc/virtualagc`

4) I was able to apply succesfully the alternative sudo stuff:
`sudo apt-get install wx3.0-headers libwxgtk3.0-dev libsdl-dev libncurses5-dev liballegro4-dev git`

5) then I compiled succesfully using these commands as suggested on your well doc. webpage:
```
cd virtualagc
make install
```

The Icon came up on my desktop of the rapbipy and I was able to start the "VirtualAGC Simulation Manager"

What can I do to get the AGC CPU BUS/INPUT/OUTPUT Monitor and its subcomponents. run and working?

Greetings from Germany,

Sacha Tholl
tholl@fh-aachen.de

**Comment by sachatholl** [comment]
Dear Rob,

Thank you very much for the insight. I will try it oit tonight and tell you what was the outcome. Maybe I can make a screenshot of the messages spoken out from the terminal.

have a nice day,
Sacha





l
l
Dipl.-Ing. Sacha Tholl
Head of FHA//SOF
Space Operations Facility
Faculty of Aerospace Engineering

FH Aachen University of Applied Sciences
Hohenstaufenallee 6
52064 Aachen
Germany

Mobile: +49 (0)163 754 666 1

Faculty web: www.fb6.fh-aachen.de
Youtube: https://www.youtube.com/channel/UCVVyDe6XZ8opbCRaNJ03Faw




This message is intended only for the recipient(s) named above. It may contain proprietary information and/or protected content. Any unauthorised disclosure, use, retention or dissemination is prohibited. If you have received this e-mail in error, please notify the sender immediately. The FH Aachen applies appropriate organisational measures to protect personal data, in case of data privacy queries, please contact the FH Aachen IT security office (it-sicherheit@fh-aachen.de).
________________________________
Von: rburkey2005 <notifications@github.com>
Gesendet: Donnerstag, 31. Oktober 2019 16:30:46
An: virtualagc/virtualagc
Cc: Tholl, Sacha; Mention
Betreff: Re: [virtualagc/virtualagc] Virtual AGC crashes when AGC CPU Bus Input/Output Monitor and/or its subcomponents are started on Raspbian Buster (#1104)


@sachatholl<https://github.com/sachatholl> I will look at this as soon as I can, but it's possible that may not be until the weekend. So in the meantime I offer the following observation, which may allow you a temporary workaround.

I suspect that the shutdown is not directly related to the receipt of the telemetry data. Rather, the way the shutdown method works is to occasionally poll the components (yaAGC, yaDSKY2, etc.) which it thinks ought to be running, and then to shut down all of the other components if it finds that any of the expected ones are missing. This process takes several seconds. Similarly, receipt of the first telemetry data takes several seconds. So it's easy for the two things to happen roughly simultaneously just through coincidence.

If that's what's happening, then the question becomes, Which component" is shutting down first and thus triggering the shutdown of everything else? Or perhaps, Which component is missing entirely, and therefore never even gets a chance to run?

There's a relatively easy way to track down the answers to these questions. When you run the simulation from the VirtualAGC GUI, it creates a script file called "simulate", with the various options you've selected, and then simply runs that script. If you choose different options, the generated "simulate" script will also be different. The script remains even after the shutdown. So instead of running VirtualAGC, you can do this from a command line:

     cd ~/VirtualAGC/Resources
     ./simulate


As I say, this is precisely the same thing that VirtualAGC itself does, with whatever options you last chose, but the advantage is now that you can see all of the messages that would otherwise be hidden from you. Seeing those messages may be able to tell you which component of the software is causing you problems.

Given that I'm not in a position to actually try this myself right now, I may have omitted some essential step ... if so, my apologies! But I think the general idea is right, and it's the first thing I'm going to try myself when I have the opportunity to look into the problem in detail.

**Comment by sachatholl** [comment]
Hi,


I started .&simulate using the terminal console, and here is the output i got;


pi@raspberrypi:~/VirtualAGC/Resources $ ./simulate
rm: cannot remove 'LM.core': No such file or directory
rm: cannot remove 'CM.core': No such file or directory
LM Abort Guidance System simulation, ver. 2019-09-22, built Oct 29 2019 22:46:37
(c)2005,2009 Ronald S. Burkey.
Refer to http://www.ibiblio.org/apollo for additional information.
Loaded 010000 (octal) 18-bit values.
Address 06000 contains the value 706177, opcode 70
./simulate: 15: ./simulate: wish: not found
Apollo Guidance Computer simulation, ver. 2019-09-22, built Oct 29 2019 22:46:31
Copyright (C) 2003-2009 Ronald S. Burkey, Onno Hommes.
yaAGC is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Refer to http://www.ibiblio.org/apollo/index.html for additional information.
yaACA2 Apollo ACA simulation, ver NVER, built Oct 29 2019 22:53:09
Copyright 2009 by Ronald S. Burkey
Refer to http://www.ibiblio.org/apollo/index.html for more information.
yaDSKY2 Apollo DSKY simulation, ver NVER, built Oct 29 2019 22:52:50
Copyright 2009,2017 by Ronald S. Burkey
Refer to http://www.ibiblio.org/apollo/index.html for more information.
Arg 1 = "--cfg=LM.ini"
yaDEDA2 Apollo DEDA simulation, ver NVER, built Oct 29 2019 22:52:32
Copyright 2009 by Ronald S. Burkey
Refer to http://www.ibiblio.org/apollo/index.html for more information.
Arg 1 = "--half-size"
Arg 2 = "--port=19797"
Hostname=localhost, port=19797
Hostname=localhost, port=19897
../src/common/sizer.cpp(1401): assert "Assert failure" failed in DoInsert(): too many items (13 > 2*6) in grid sizer (maybe you should omit the number of either rows or columns?)
yaDEDA2 is connected, socket=5.
Adding socket 13 on port 19897

yaTelemetry build Oct 29 2019 22:53:28, Copyright 2009 Ronald Burkey
For more information, consult http://www.ibiblio.org/apollo.
     --delay=0
     --port=19800
     --ip=localhost
     --spacecraft=LM
     --font-size=11
yaDSKY is connected.
     height=948
Adding socket 13 on port 19797
yaTelemetry is connected.
Adding socket 14 on port 19800
yaACA2 is connected, socket=9.
Adding socket 15 on port 19803
GREP=grep
Scanning for program status of processes 9205 9204 9203 9202 9201 9200 9199
Process 9204 has terminated.
Bye! Shutting down the simulation.
../bin/SimStop: 67: kill: No such process





PS: Should I make a copy of this raspberrypi image? It's a virgin Raspbian buster distro with only VirtualAGC installed.


Thank you very much for your help,

Greetings,

Sacha





________________________________
Von: rburkey2005 <notifications@github.com>
Gesendet: Donnerstag, 31. Oktober 2019 16:30
An: virtualagc/virtualagc
Cc: Tholl, Sacha; Mention
Betreff: Re: [virtualagc/virtualagc] Virtual AGC crashes when AGC CPU Bus Input/Output Monitor and/or its subcomponents are started on Raspbian Buster (#1104)


@sachatholl<https://github.com/sachatholl> I will look at this as soon as I can, but it's possible that may not be until the weekend. So in the meantime I offer the following observation, which may allow you a temporary workaround.

I suspect that the shutdown is not directly related to the receipt of the telemetry data. Rather, the way the shutdown method works is to occasionally poll the components (yaAGC, yaDSKY2, etc.) which it thinks ought to be running, and then to shut down all of the other components if it finds that any of the expected ones are missing. This process takes several seconds. Similarly, receipt of the first telemetry data takes several seconds. So it's easy for the two things to happen roughly simultaneously just through coincidence.

If that's what's happening, then the question becomes, Which component" is shutting down first and thus triggering the shutdown of everything else? Or perhaps, Which component is missing entirely, and therefore never even gets a chance to run?

There's a relatively easy way to track down the answers to these questions. When you run the simulation from the VirtualAGC GUI, it creates a script file called "simulate", with the various options you've selected, and then simply runs that script. If you choose different options, the generated "simulate" script will also be different. The script remains even after the shutdown. So instead of running VirtualAGC, you can do this from a command line:

     cd ~/VirtualAGC/Resources
     ./simulate


As I say, this is precisely the same thing that VirtualAGC itself does, with whatever options you last chose, but the advantage is now that you can see all of the messages that would otherwise be hidden from you. Seeing those messages may be able to tell you which component of the software is causing you problems.

Given that I'm not in a position to actually try this myself right now, I may have omitted some essential step ... if so, my apologies! But I think the general idea is right, and it's the first thing I'm going to try myself when I have the opportunity to look into the problem in detail.

**Comment by rburkey2005** [comment]
From the message "./simulate: 15: ./simulate: wish: not found", it appears to me that Tcl/Tk may not be installed, or perhaps not fully installed.  That's because "wish" is part of Tk.  Try installing it with

```
sudo apt-get update
sudo apt-get install tcl tk
```

I don't actually have a Pi with Raspbian Buster installed right now, so I'm not entirely sure those are the right commands to do the installation.  Another thing you can do, in the VirtualAGC GUI rather than the command line, is to try unchecking "AGC CPU Bus/InputOutput Monitor".  That's the only thing that actually depends on Tcl/Tk.

**Comment by rburkey2005** [comment]
Sorry, I forgot that what you were trying to do is to get  "AGC CPU Bus/InputOutput Monitor" working.  :smile:  So _don't_ try unchecking that.

**Comment by sachatholl** [comment]
Hi Ron,


Done! It works. After having performed on your advice, an update, then install tcl tk,

now everything seems to works, as far as I can evaluate as an AGC rooky.

Now, I have to read a lot of documentation to learn to fly :-)

[cid:0a98c932-c584-40c8-8af1-66943df8c32e]

Thank you so much,

Greetings from Germany,

Sacha

**Comment by rburkey2005** [comment]
Glad to hear it!  I'll modify the instructions to indicate that it may be necessary to explicitly install Tcl/Tk.
