### ISSUE TITLE
Reconstruct MANCHE45 rev 2 from Comanche 45

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#1138]
### Branch
[manche45r2](https://github.com/virtualagc/virtualagc/tree/manche45r2)

### Changed Bugger Words from Closest Program (Comanche 045)
```
Bugger word mismatch in bank 11; actual 44661 != expected 66053 (diff = 21172)
Bugger word mismatch in bank 12; actual 51215 != expected 35701 (diff = 13314)
Bugger word mismatch in bank 13; actual 74770 != expected 65527 (diff = 07241)
```

### Known Differences
- Implementation of the R-2 lunar potential model.

### Resources
- [Comanche 55 listing](https://archive.org/details/Comanche55J2k60)

### Notes
This one is easy! The changes from 45 to 45/2 are 100% identical to the changes between 51 and 55.

**Comment by thewonderidiot** [comment]
### Comparison of MANCHE45/2 with COMANCHE 45

An appendix of the GAP User's Manual shows off an example of GAP's binary diffing capabilities, using MANCHE45/2 and COMANCHE 45 as its demo ropes. And fortunately for us, all four pages of diffs are included.
![c45r2_pg2](https://user-images.githubusercontent.com/94056/131205081-ce471b9a-a382-4520-841e-740a85f6e129.png)
![c45r2_pg3](https://user-images.githubusercontent.com/94056/131205085-750f57a3-6a23-45a5-80a7-d7737c907e56.png)
![c45r2_pg4](https://user-images.githubusercontent.com/94056/131205088-a8811d17-877c-43ed-9337-3bc571f589fe.png)
![c45r2_pg5](https://user-images.githubusercontent.com/94056/131205091-df992365-0321-4be0-8289-37992c8cf84e.png)

In these dumps, every word that is not identical (`=`) is listed with 45/2 on the left and 45 on the right. Our own modern equivalent of this is `bdiffhead`, which produces the following output:
```
File Manche45R2.bin is Block 2.
File Comanche045.bin is Block 2.
0023130 (11,3130):         40161 77761
0023132 (11,3132):         23133 00033
0023136 (11,3136):         53670 43070
0023140 (11,3140):         20153 00343
0023141 (11,3141):         40055 23210
0023142 (11,3142):         02202 63545
0023143 (11,3143):         22762 00017
0023144 (11,3144):         36202 63525
0023145 (11,3145):         27770 00021
0023146 (11,3146):         77716 65215
0023147 (11,3147):         41206 00003
0023150 (11,3150):         27755 45352
0023151 (11,3151):         60525 00003
0023152 (11,3152):         44215 41525
0023153 (11,3153):         00011 00023
0023154 (11,3154):         11613 65361
0023155 (11,3155):         41205 00025
0023156 (11,3156):         00017 45316
0023157 (11,3157):         27755 23746
0023160 (11,3160):         56561 52405
0023161 (11,3161):         00017 27755
0023162 (11,3162):         77725 52361
0023163 (11,3163):         43225 02152
0023164 (11,3164):         11613 72561
0023165 (11,3165):         00011 77725
0023166 (11,3166):         14011 00017
0023167 (11,3167):         00017 63205
0023170 (11,3170):         41205 00021
0023171 (11,3171):         00023 02152
0023172 (11,3172):         27755 74235
0023173 (11,3173):         43352 00025
0023174 (11,3174):         60325 53332
0023175 (11,3175):         02310 77725
0023176 (11,3176):         00050 41301
0023177 (11,3177):         67206 00050
0023200 (11,3200):         01775 00001
0023201 (11,3201):         74271 74265
0023202 (11,3202):         53257 27753
0023203 (11,3203):         57601 53257
0023204 (11,3204):         70257 57605
0023205 (11,3205):         20146 00033
0023206 (11,3206):         65325 77754
0023207 (11,3207):         01517 02150
0023210 (11,3210):         27755 77600
0023211 (11,3211):         45154 23212
0023212 (11,3212):         02150 53257
0023213 (11,3213):         55344 20153
0023214 (11,3214):         40055 02202
0023216 (11,3216):         22762 77600
0023217 (11,3217):         02202 22762
0023777 (11,3777):         66053 44661
0025754 (12,3754):         63525 03754
0025755 (12,3755):         00021 03755
0025756 (12,3756):         77625 51215
0025757 (12,3757):         74205 00000
0025760 (12,3760):         27755 00000
0025761 (12,3761):         00017 00000
0025762 (12,3762):         65332 00000
0025763 (12,3763):         00017 00000
0025764 (12,3764):         43342 00000
0025765 (12,3765):         00003 00000
0025766 (12,3766):         14003 00000
0025767 (12,3767):         00021 00000
0025770 (12,3770):         44342 00000
0025771 (12,3771):         00005 00000
0025772 (12,3772):         00005 00000
0025773 (12,3773):         74335 00000
0025774 (12,3774):         01774 00000
0025775 (12,3775):         43525 00000
0025776 (12,3776):         00023 00000
0025777 (12,3777):         35701 00000
0027742 (13,3742):         77651 00000
0027743 (13,3743):         76237 00000
0027770 (13,3770):         71214 03770
0027771 (13,3771):         00343 03771
0027772 (13,3772):         23220 74770
0027773 (13,3773):         00017 00000
0027774 (13,3774):         52116 00000
0027775 (13,3775):         25754 00000
0027776 (13,3776):         03776 00000
0027777 (13,3777):         65527 00000
```

I've gone through this a couple of times, and our `bdiffhead` output is identical to the GAP comparison output, which means that our reconstruction steps to go from 45 to 45/2 are confirmed to be exactly correct.

**Comment by rburkey2005** [comment]
@thewonderidiot I doubt you need much validation from me at this point &mdash; if you ever did &mdash; but obviously this is great news!  I would also say, not having had to personally spend any time and effort on it myself, that I'm _glad_ that the software was first reconstructed from PCRs the way it was.  (As opposed to just relying the octal diffs and disassembling the octals to get the source code.)  It ends up giving a lot more confidence in the reconstruction technique.
