### ISSUE TITLE
Reconstruction of CORONA 261

### ISSUE THREAD

**Issue by rburkey2005** [virtualagc/virtualagc#1153]
I have no intention of trying to reconstruct CORONA 261 myself, particularly since we have no knowledge of its checksums as far as I know, but someone might want to.  And if we ever get the long-awaited dump of its core modules, someone will want to decompile it and mix-and-match with SOLARIUM to recover the source code.  At any rate, I thought there should be some place-holder for that, in which helpful resources could at least be taken note of.

I see that in [E-1142 rev 45](https://www.ibiblio.org/apollo/Documents/E1142-45.pdf#page=43), there's a table that lists all the log sections of CORONA, along with the number of words of fixed memory those sections use.  At that point, it also seemed to believe that CORONA would be used for Apollo 4 and Apollo 6, implying that the differences between CORONA and SOLARIUM are likely very small.  My thought is that if one had a list of the number of words of fixed memory each section of SOLARIUM 55 uses, one might find that most of the sections were unchanged in length, and hence might be unchanged.

**Comment by indy91** [comment]
And there is this handy list of changes between AS-202 and AS-501: https://www.ibiblio.org/apollo/Documents/Programming%20Changes%20from%20AS-202%20to%20AS-501.pdf

**Comment by rburkey2005** [comment]
E-1142 unfortunately does not specify the CORONA revision number, but the document is from June 1966, and AS-202 was intended to launch in July 1966 (though it slipped to August), so the revision it lists _might_ be 261.

While we don't have a list of CORONA ropes manufactured, I see that the 1969 document covering the [K-START tape system](https://www.ibiblio.org/apollo/Documents/kstart_numbering.pdf#page-3), which apparently was used to store those core-rope images, does indeed list 261 as the unique CORONA release (as well as listing 69 as the unique SUNRISE release, by the way).  So possibly (or not) that strengthens the case that E-1142 is discussing CORONA 261.

**Comment by rburkey2005** [comment]
I see as well that [E-1142 rev 44](https://www.ibiblio.org/apollo/Documents/E1142-44.pdf#page=44) from May, exactly a month prior, lists the identical table of fixed-word usage.  So if CORONA was changing, must not have changed much from May to June 1966.

**Comment by rburkey2005** [comment]
And indeed, the identical table is listed in [E-1142 rev 46, July 15, 1966](https://www.ibiblio.org/apollo/Documents/E1142-46.pdf#page=46).

This July 15 document also lists the fixed-memory usage for "CORONA FLIGHT AS-501 AND AS-502", though those values obviously are not of much interest.

**Comment by rburkey2005** [comment]
And in [E-1142 rev 47, August 15.1966](https://www.ibiblio.org/apollo/Documents/E1142-47.pdf#page=39).  I think we have to admit that this really is CORONA 261.

Although at this point, I can see the error in my wishful thinking.  Comparing the fixed-memory usage of CORONA 261 to what the preliminary tables in these documents are telling us about SOLARIUM, all the sections I've checked have changed.  There is no large pool of unchanged memory sections.  Admittedly, many of them may not have changed by _much_, but they've nevetheless changed somewhat.

By the way, I also see that SUNSPOT (Apollo 1), SUNDIAL, and AURORA fixed-memory allocations are beginning to be listed by this point.  So I guess the SUNSPOT numbers could come in handy at some point.

**Comment by rburkey2005** [comment]
[This paper](https://www.ibiblio.org/apollo/hrst/archive/1120.pdf#page=5) mentions that CORONA was released in January 1966.

**Comment by thewonderidiot** [comment]
Closing since we now have dumps of Corona 261 from the flown rope modules.
