### ISSUE TITLE
AEA emulation bug (MPR opcode)

### ISSUE THREAD

**Issue by spacex15** [virtualagc/virtualagc#1154]
Hello all,

I think I identified a problem in the AEA emulation code for the MPR opcode

the rounding code below causes problems

if (OpCode != 006)		// Don't round for MPY
{
    if (State->Quotient & 0200000)
	State->Accumulator++;  
}

this is dangerous when State->Accumulator is 0777777 because it causes a catastrophic overflow
the accumulator is not supposed to exceed 18 bits
adding one to 0777777 causes a 19 bit accumulator value
this happens for small negative values and I saw it happen when trying to update AGS state vector with radar updates in NASSP

I suggest to replace the above code with

if (OpCode != 006)		// Don't round for MPY
{
    if (State->Quotient & 0200000)
    {
        if (State->Accumulator != 0777777)
             State->Accumulator++;
	else State->Accumulator = 0;
    }
}

with this version, radar updates are working much better and the code still passes self test successfully

On another topic

I read the ags documentation page on the virtual agc website and do not understand the following comment

"Perhaps the most confusing thing is that while the portion of the document that covers the LEMAP assembler makes 
it clear that the integer -1 would be encoded in octal as 0777777 (as anyone working with a modern PC would expect),
 the portion of the document that covers assembly language repeatedly refers to the octal 0400000 as being "-1".
   (More specifically, the reference on these occasions is to "A0 = 1, A1 thru A17 = 0", where A0 is the sign bit and A1-A17 are the data bits.)
  In fact, this octal pattern encodes the "largest" 18-bit negative number, namely -131072.
  In this detail, the assembly-language portion of the manual is thus incorrect.
"

Actually i do think that when they say in the document that -1 is octal 0400000, you have to actually interpret the -1 as -1.0000000 
(the largest negative floating number to be managed in the AEA) and thus the manual in my opinion is correct
0777777 would be the smallest negative floating number to te managed ie -0.000007629394531 (-1/131072)

**Comment by rburkey2005** [comment]
Good job!  I've both pushed a change to yaAGS.c with the fix you recommended, and a change to the AGS page of the website in which I moderated my language about the original documentation as you suggest.

I'm not entirely convinced that the software fix is the correct one, but it doesn't seem unreasonable, so I happy to use it.

Thanks!

**Comment by indy91** [comment]
Hey @spacex15 awesome find! So what you are saying is this fixes the issue we have with FP8 when sending RR updates from the PGNS to the AGS? Because that strangely wasn't really working, while the normal state vector "downlink" from PGNS to AGS in any flight program always worked fine. And from an emulator and simulator perspective those two types of sending data from PGNS to AGS should be identical. But it makes sense that it would be caused by a rare, very specific AEA bug!

**Comment by thewonderidiot** [comment]
I concur with both the bug and the fix. This was an excellent find, thanks so much @spacex15 !
