### ISSUE TITLE
Reconstruct MANCHE72 rev 3 from Comanche 72

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#1180]
### Branch
TBD

### Changed Bugger Words from Closest Program (Comanche 72)
```
Bugger word mismatch in bank 06; actual 56652 != expected 50373 (diff = 06257)
Bugger word mismatch in bank 11; actual 73473 != expected 51224 (diff = 22247)
make: *** [Makefile:21: diffComanche072sums] Error 2
```

### Known Differences (from Apollo 13 FSRR slides)
* PCR 984 -- Avoid Coarse Align during Saturn

### Resources
* [PCN 1041](https://www.ibiblio.org/apollo/Documents/PCN-1041.pdf)
* [Colossus Memo 226 - Revisions 102 through 104](https://www.ibiblio.org/apollo/Documents/COL-unnumbered-042770.pdf)
* [Apollo 13 FSRR Material](https://www.ibiblio.org/apollo/Documents/apollo_13_fsrr_slides.pdf)
* [Artemis 72 program listing](https://archive.org/details/Artemis072J2k60)

### Notes
According to the FSRR slides, MANCHE72 rev 3 differs from Comanche 72 by only a single change -- PCR 984. We don't have a copy of PCR 984 itself, but we _do_ have a copy of PCN 1041, which was a modification of PCR 984. 

Artemis 72 includes the code for both PCR 984 and PCN 1041 in the [T4RUPT PROGRAM](https://github.com/virtualagc/virtualagc/blob/master/Artemis072/T4RUPT_PROGRAM.agc#L596) section. It's easy to identify as such because [Colossus Memo 226](https://www.ibiblio.org/apollo/Documents/COL-unnumbered-042770.pdf) details the implementation of PCR 984 and PCN 1041 in Comanche 102-104.
```AGC
		EBANK=	DAPDATR1
		CAF	EBANK6
		TS	EBANK
		CS	DAPDATR1
		MASK	PRIO30
		CCS	A
		TCF	CALLCRS			# NO

		CAF	AVEGBIT			# YES, IS AVEG ON
		MASK	FLAGWRD1
		CCS	A
		TCF	NOGIMRUN		# YES, DON'T COARSE ALIGN
```

The second chunk of this code is from PCN 1041, which was not incorporated into MANCHE72. So, the trick with this one is to figure out (a) how the above code looks different without the second chunk, and (b) how they managed to fit this into one module without breaking other modules.

Bank 6 is where this code should normally go, but I believe that there is simply no room in that bank in Comanche 72. As such, I think that the bulk of this code was inserted into the end of bank 11, with code to transfer between them. This code is running in an interrupt so care must be taken (i.e. `BANKCALL` can't be used). 

It just so happens that there's [an existing IBNKCALL](https://github.com/virtualagc/virtualagc/blob/master/Comanche055/T4RUPT_PROGRAM.agc#L620) to `SETCOARS` right at the point where a bank change to the new code would be desired. I have a sneaking suspicion that perhaps this was changed to jump to bank 11 instead, so I think that would be a good first angle of attack.

**Comment by thewonderidiot** [comment]
The primary difficulty for this one turns out to be solving the jump to bank 11 from bank 6. For starters, let's define a label at the end of bank 11 which we can target with jumps. At the end of RTB_OP_CODES.agc (where the Comanche 55 module change for the gravity model was inserted):
```AGC
		BANK	11
		BANK
		COUNT*	$$/T4RPT

GLOCKCK1	EQUALS
```

My suspicion turned out to be incorrect; changing the target of the existing IBNKCALL to jump to `GLOCKCK1` instead of `SETCOARS` leaves reasonably high checksum error in bank 6:
```
../Tools/check_buggers.py Manche72R3.bin Manche72R3.buggers
Bugger word mismatch in bank 06; actual 51721 != expected 50373 (diff = 01326)
Bugger word mismatch in bank 11; actual 73473 != expected 51224 (diff = 22247)
make: *** [Makefile:20: diffManche72R3sums] Error 2
```
This error gets worse if we try to replace the IBNKCALL with POSTJUMP (up to 01357).

So, we need to find a different way to do it. There are two possibilities that I can think of:
1. A single instruction in GLOCKMON got replaced with a jump to the end of bank 6, which then jumps GLOCKCK1 in bank 11 (possibly after some processing).
2. Two instructions were replaced with a TC IBNKCALL/CADR GLOCKCK1 sequence.

In my opinion, option 1 is overly convoluted and unlikely to be the solution. So, let's investigate option 2 and look at where we can insert an IBNKCALL into GLOCKMON:
```AGC
GLOCKCHK	AD	-70DEGS
		EXTEND
		BZMF	SETGLOCK -1		# NO LOCK.

		AD	-15DEGS			# SEE IF ABS(MGA) GREATER THAN 85 DEGS.
		EXTEND
		BZMF	NOGIMRUN

		CAF	BIT4			# IF SO, SYSTEM SHOULD BE IN COARSE ALIGN
		EXTEND				# TO PREVENT GIMBAL RUN-AWAY.
		RAND	CHAN12
		CCS	A
		TCF	NOGIMRUN

 (PCR 984 inserted here in Artemis)

		TC	IBNKCALL		# GO INTO COARSE ALIGN.
		CADR	SETCOARS
```

To exactly preserve program flow, we need our PCR 984 code to follow the `CCS A; TCF NOGIMRUN`, and precede the `TC IBNKCALL; CADR SETCOARS`. This _really_ does not leave us with a lot of options, if we're replacing two whole words. In fact, the only option I can think of is to replace the `CCS A; TCF NOGIMRUN` itself with our jump. Replacing anything earlier would cause our PCR 984 code to be executed too early, unless we jump over the dead code we create. So let's try that:

```AGC
		CAF	BIT4			# IF SO, SYSTEM SHOULD BE IN COARSE ALIGN
		EXTEND				# TO PREVENT GIMBAL RUN-AWAY.
		RAND	CHAN12
		TC	IBNKCALL
		CADR	GLOCKCK1

CALLCRS		TC	IBNKCALL		# GO INTO COARSE ALIGN
		CADR	SETCOARS
```

Note that I've added in the `CALLCRS` label from Artemis. This fully resolves the bank 6 checksum:
```
../Tools/check_buggers.py Manche72R3.bin Manche72R3.buggers
Bugger word mismatch in bank 11; actual 73473 != expected 51224 (diff = 22247)
make: *** [Makefile:20: diffManche72R3sums] Error 1
```
I think this is a very good sign that option 2 is correct.

Because we replaced the `CCS A; TCF NOGIMRUN` with our jump, that code is going to need to go at the beginning of our GLOCKCK1, followed by the PCR-984 code we're inserting. So, let's start by copying all of the relevant code from Artemis. We will then tweak it to remove PCN-1041 and make it work out of bank 11.
```AGC
GLOCKCK1	CCS	A
		TCF	NOGIMRUN

		EBANK=	DAPDATR1
		CAF	EBANK6
		TS	EBANK
		CS	DAPDATR1
		MASK	PRIO30
		CCS	A
		TCF	CALLCRS			# NO

		CAF	AVEGBIT			# YES, IS AVEG ON
		MASK	FLAGWRD1
		CCS	A
		TCF	NOGIMRUN		# YES, DON'T COARSE ALIGN

 (Artemis falls into CALLCRS here)
```

The first step is to remove PCN-1041, which added the AVEGBIT checking at the end. Without PCN-1041, the code should proceed unconditionally to NOGIMRUN. Note, however, that CALLCRS immediately follows this code rather than NOGIMRUN; this means that we must preserve the `TCF NOGIMRUN` and instead only delete the three instructions preceding it. That gets us down to PCR-984-only code:
```AGC
GLOCKCK1	CCS	A
		TCF	NOGIMRUN

		EBANK=	DAPDATR1
		CAF	EBANK6
		TS	EBANK
		CS	DAPDATR1
		MASK	PRIO30
		CCS	A
		TCF	CALLCRS			# NO

		TCF	NOGIMRUN		# YES, DON'T COARSE ALIGN
```

We now have to deal with the fact that `NOGIMRUN` and `CALLCRS` are both in a different bank, and therefore we cannot `TCF` directly to them. This is easy for the second appearance of `TCF NOGIMRUN` -- we can replace that with a `TC IBNKCALL; CADR NOGIMRUN`:
```AGC
GLOCKCK1	CCS	A
		TCF	NOGIMRUN

		EBANK=	DAPDATR1
		CAF	EBANK6
		TS	EBANK
		CS	DAPDATR1
		MASK	PRIO30
		CCS	A
		TCF	CALLCRS			# NO

		TC	IBNKCALL		# YES, DON'T COARSE ALIGN
		CADR	NOGIMRUN
```
However we can't do the same trick for the first `TCF NOGIMRUN` because the `CCS` only skips a single instruction. So instead, let's change the target of the TCF to the IBNKCALL we just added:
```AGC
GLOCKCK1	CCS	A
		TCF	NOGIM

		EBANK=	DAPDATR1
		CAF	EBANK6
		TS	EBANK
		CS	DAPDATR1
		MASK	PRIO30
		CCS	A
		TCF	CALLCRS			# NO

NOGIM		TC	IBNKCALL		# YES, DON'T COARSE ALIGN
		CADR	NOGIMRUN
```

The `TCF CALLCRS` runs into the same issue -- the `CCS` makes it so that we can't simply replace it directly with `TC IBNKCALL; CADR CALLCRS`. Instead, let's solve it effectively the same way, by sticking the IBNKCALL at the end and `TCF`ing to that instead:
```AGC
GLOCKCK1	CCS	A
		TCF	NOGIMRN1

		EBANK=	DAPDATR1
		CAF	EBANK6
		TS	EBANK
		CS	DAPDATR1
		MASK	PRIO30
		CCS	A
		TCF	CALLCRS1			# NO

NOGIMRN1	TC	IBNKCALL		# YES, DON'T COARSE ALIGN
		CADR	NOGIMRUN

CALLCRS1	TC	IBNKCALL
		CADR	CALLCRS
```

With these changes, the code we're left with encapsulates only PCR-984, and is valid in bank 11. Assembling it gives exactly correct checksums:
```
mike@eclipse:~/virtualagc/Manche72R3$ make
../yaYUL/yaYUL --unpound-page --parity MAIN.agc >MAIN.agc.lst
mv -f MAIN.agc.bin Manche72R3.bin
mv MAIN.agc.lst Manche72R3.lst
mv MAIN.agc.symtab Manche72R3.symtab
../Tools/check_buggers.py Manche72R3.bin Manche72R3.buggers
mike@eclipse:~/virtualagc/Manche72R3$
```

**Comment by rburkey2005** [comment]
:+1:
