### ISSUE TITLE
Greetings. Apollo Guidance Computer Issue.

### ISSUE THREAD

**Issue by NickDeBeenAIE** [virtualagc/virtualagc#1185]
I had to re-install Windows 10 Pro onto a large NVMe.

So yeah, I have indeed lost not only the VirtualAGC I manually coded, but also my memory on this program.

**Comment by NickDeBeenAIE** [comment]
By the way, long time no chat nor see Rob, I hope your well.

**Comment by rburkey2005** [comment]
@NickDeBeenAIE I'm so sorry to hear that!

But I'm confused as to why you're filing a problem report about this?  It doesn't seem there's anything we're in a position to do about it.
