### ISSUE TITLE
LVDC may not boot to HOP constant at 000

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#1203]
Opening this as an issue, because I haven't quite convinced myself enough yet to do it as a pull request --

The laboratory maintenance instructions for the LVDC clearly, unambiguously state that it boots using a HOP constant stored at 000:
![image](https://github.com/virtualagc/virtualagc/assets/94056/4af17dc2-be40-4f6a-ae65-a01d69278d45)

However, no matter how hard I try I can't reconcile this statement with the more verbose descriptions that follow. My [gate-level LVDC simulator](https://github.com/thewonderidiot/lvdc_simulation) begins execution at 000, just like the PTC, and I despite my best efforts I can't find a logic transcription error, and can't find a way the hop constant stored at 000 would work. So I'm going to lay out what I'm seeing, in hopes that either it makes sense, or an error becomes obvious.

Starting with the run latch:
![image](https://github.com/virtualagc/virtualagc/assets/94056/bbd079ee-2d48-4b1d-b409-a954de7d9e63)

This description (up until the claim about the HOP constant) is consistent with what I see in the simulator. Each A-6-Y time, the run latch becomes set. As long as HALTV is asserted, it immediately becomes unset at time A-6-Z.
![image](https://github.com/virtualagc/virtualagc/assets/94056/93f50738-3e49-431f-bf80-5549a717f9a2)

When HALTV is deasserted, the run latch becomes set at the next A-6-Y time, and remains set.
![image](https://github.com/virtualagc/virtualagc/assets/94056/7b94b706-715a-422e-b065-621406136fa8)

Continuing on with the next paragraph, which describes what happens when HALTV is applied to a running LVDC:
![image](https://github.com/virtualagc/virtualagc/assets/94056/39070450-5fca-45ed-b7ea-8d06210cbf29)

> The run latch disables memory during phase A, consequently instruction words cannot be read from memory.

This is accomplished through gate A16 in the Memory OPerate (MOP) gate:
![image](https://github.com/virtualagc/virtualagc/assets/94056/aa1fa8ce-ccae-4da3-890b-6455d99c3ed4)

This AND gate has inputs PAV (phase A), G6V (a timing signal that is high during bit times 6 through 12), and RUNVN (which goes high when the run latch is reset). The output of this gate going high forces MOP low through the inverter. Interestingly, this is less restrictive than the text makes it out to be, since memory operation is only inhibited in bit times 6 through 12 of phase A, instead of the entirety of it. 

To understand that, we need to look at the SINK latch, which kicks off memory cycles. They can happen at a number of different times, and always arrive in pairs (one memory cycle for a read, and one memory cycle for a writeback). A complete LVDC instruction has 6 SINK pulses -- two each for the instruction access, the syllable 0 access, and the syllable 1 access. Here is the full SYNC latch with possible pulse times annotated:
![image](https://github.com/virtualagc/virtualagc/assets/94056/0e4d6a4a-7f05-4a3b-b2ec-cfcd37cb0e3a)

Most times require MOP to be high to set the latch. The couple that don't depend on RD, which itself requires MOP to be high:
![image](https://github.com/virtualagc/virtualagc/assets/94056/3a433f3d-c468-4314-8e22-209956c27abe)

These time gates and their dependencies on RD and INHBS produce the following SINK waveforms, for read and store instructions respectively:
![image](https://github.com/virtualagc/virtualagc/assets/94056/314c66d5-4e27-4802-a11d-ca9274527eb2)
![image](https://github.com/virtualagc/virtualagc/assets/94056/c536586b-da60-4d7b-b5ff-bc0cffaf927b)

For both types of cycles, the instruction read happens at times A-7-Z and A-10-Z, which is fully covered by our PAV & G6V & RUNVN inhibition period. If the LVDC were to try to execute a read instruction (like HOP) here, the next SINK pulse to begin reading syllable 0 of the data would begin at time A-13-Z, after our inhibition period has expired. So it must be stopped by a different mechanism.

Moving on to the next few sentences:
> The transfer register and in turn the OP code and address registers will be loaded with "0's", this commanding a HOP to 000. When the HOP code is loaded into the OP code register the HOP latch becomes set. When both HOP and RUNVN equal "1" memory operation is also disabled during phases B and C.

As with the last sentence, these are a bit of an oversimplification, and somewhat misleading. The order of events here actually starts with the OP code registers. Looking at OP1 as a specific example:
![image](https://github.com/virtualagc/virtualagc/assets/94056/2b7873b9-c5d1-47bf-852e-0c3cd88b95f9)

The OP code register is cleared to all zero (i.e., HOP) at every time A-5-Y. It isn't loaded with the contents of the transfer register until time A-12-Y. This means that for 7 bit times, the OP code register temporarily reads as HOP between every instruction. Because our RUN latch didn't become unset until time A-6-Z, the OP code register is already set up for HOP.

At time A-12-Y, the OP code register gets filled with the contents of the transfer register. The transfer register itself is usually filled by the contents of the memory buffer registers BRA or BRB at time under control of the TBR latch. For instructions, this happens at time A-11-W. But our BRA and BRB registers are both 0, since the usual instruction read memory cycle was inhibited. So none of the opcode bits in the transfer register become set, and the OP code register itself remains 0.

Next up is the HOP latch. It is reset at every A-6-Z, and becomes set (indicating a real, actual HOP) at time A-12-Z if all of the OP code register bits are 0. 
![image](https://github.com/virtualagc/virtualagc/assets/94056/1e5c083c-e37f-499c-962d-00fd0d3692af)

This finally brings us back around to the statement,
> When both HOP and RUNVN equal "1" memory operation is also disabled during phases B and C.

Going back the MOP gate, this condition is handled by gate A24:
![image](https://github.com/virtualagc/virtualagc/assets/94056/d74246ce-f5a5-4c4b-a7d4-8e67f997a74e)

Notably as long as these two signals are high, _all_ memory accesses are now disabled, even during phase A. With no memory accesses enabled, the transfer register will be repeatedly loaded with 0s from the memory buffer registers, and these 0s will be sent through the usual circulation loop. Under control of the HOP logic, these 0s will be treated as a HOP constant and picked off of the circulation loop and placed into their addressing registers at the designated times. Here's a screenshot of the simulator where you can see this whole process, starting from HALTV assertion in action:
![image](https://github.com/virtualagc/virtualagc/assets/94056/49e483c4-2646-4c55-8c39-639342e179a1)

Once the HOP line goes high, all of the various module, sector, address, etc. registers begin to be set to 0 by the circulating 0 "hop constant". This loop proceeds ad infinitum until either a CLA/STO instruction is injected by the GSE, or the HALTV line is deasserted allowing the run latch to become set.

**Summary 1:** When the computer is placed into reset by assertion of HALTV,  the process begins at time A-6-Z. Memory cycles are fully inhibited by time A-12-Z, at the moment HOP is selected as the next instruction to run. If a HOP constant stored at location 000 were to be used when the computer goes into reset, the memory cycles occurring in times B and C would need  to remain enabled for at least one full instruction cycle after the RUN latch becomes reset. But because memory cycles are fully inhibited at A-12-Z, no HOP constant can be loaded from memory so long as the RUN latch remains reset.

Next, let's look at what happens when HALTV is deasserted. This case is much simpler because of the timing of the RUN latch. As discussed above, the RUN latch becomes briefly set every time A-6-Y, regardless of the status of HALTV. With HALTV now low, it will remain asserted. As soon as this happens, all memory inhibits are released.

The timing of this is key. Memory cycles to load instructions begin at time A-7-Z. Since the RUN latch became set at A-6-Y, _the very first_ possible instruction read cycle after HALTV is released is performed.
![image](https://github.com/virtualagc/virtualagc/assets/94056/90018df9-62d1-4b87-be7e-7436a6ca6ce1)

**Summary 2:** The forced, "simulated" HOP instruction does not persist into the first instruction after a reset. This instruction is loaded from address 000 due to the action of the simulated HOP. If a HOP constant were instead to be loaded from address 000 after HALTV is released, the phase A memory cycle to load instructions would need to remain inhibited to maintain the selection of HOP as the current opcode. However, there is no such condition on the MOP gate.

Given this, I don't think it is possible for a HOP constant to be automatically loaded from 000, either at the time reset is applied, or at the time it is released. I think the LVDC must boot just like the PTC, with execution beginning with the _instruction_ stored at 000.

**Comment by rburkey2005** [comment]
This isn't a critique of the preceding comment, but just some extra information that I had to track down myself and wanted to memorialize.  The laboratory maintenance manual referenced is this:

- [Volume 1](https://www.ibiblio.org/apollo/Documents/LaboratoryMaintenanceInstructionsForLVDC-Volume1-GeneralDescriptionAndTheory.pdf)
- [Volume 2](https://www.ibiblio.org/apollo/Documents/LaboratoryMaintenanceInstructionsForLVDC-Volume2-MaintenanceData.pdf)

This manual is dated 30 NOVEMBER 1964 and updated 4 JANUARY 1965.  

Though I knew that it was unlikely, my immediate thought was that the descriptions in the document text (which repeatedly talk about the HOP constant at address 0) and the logic diagrams may be out of sync.  I.e., since the PTC (earlier) is supposed to boot to address 0, while the LVDC (later) is supposed to perform a HOP 0 on boot, perhaps the diagrams reflect the PTC and the descriptions reflect the LVDC.  

However, that notion doesn't seem to be correct:  If you look at the change log for the document (p. 2 of volume 1), you can see that paragraphs 2-249 and 2-250 referenced above are on p. 2-105, and that p. 2-105 is original ... i.e., unchanged when the document was revised. So if the diagrams and the text are out of sync, they must have been out of sync even in the very first release of the document.  

Which is, of course, still logically possible.

The manual does state explicitly that it is for the "breadboard model II" of the LVDC, rather than for the flight model.  There are some differences (listed in the document) between the two, but even if they differed it still wouldn't account for differences between the textual description and the diagrams.

**Comment by rburkey2005** [comment]
I don't recall what I was thinking when I originally coded the LVDC CPU emulator, but this language "HOP to 000" does not suggest to my mind _now_ that a "HOP 0" is executed.  Rather, it suggests that execution begins at 0.

Is there anyplace other than the final sentence in paragraph 2-249 suggesting that address 0 contains a HOP constant?

**Comment by thewonderidiot** [comment]
Nope, it's just that one, single sentence. As far as I can tell everything else implicitly suggests execution starts at 0. 

I thought about these schematics potentially being outdated relative to the flight LVDC too -- and in a way, they are, because outside of the clock logic most of the circuitry is single-string instead of triplicated. But nothing I have found so far leads to a behavioral difference between this simplex model and the flight LVDC.

**Comment by rburkey2005** [comment]
Well, the main (or only?) difference listed between the breadboard model II and the production computer is that the breadboard model II lacks redundancy and the associated voting, so if that's the triplication you're talking about, it would be exactly as expected.

I'm certainly willing to believe that the HOP-constant-at-000 thing is just wrong.

**Comment by thewonderidiot** [comment]
> Well, the main (or only?) difference listed between the breadboard model II and the production computer is that the breadboard model II lacks redundancy and the associated voting, so if that's the triplication you're talking about, it would be exactly as expected.

Yeah. Interestingly, and counterintuitively (to me at least), this breadboard model _does_ have full all of the duplex memory features. It's just the triple redundancy and logic voting that are missing. They kind of overloaded the word "simplex" there.

> I'm certainly willing to believe that the HOP-constant-at-000 thing is just wrong.

Okay, I'll submit a PR with the change shortly.

**Comment by rburkey2005** [comment]
If we're right, then it would seem the IM, IS, and S get set predictably upon power-up or reset, but do DM and DS?  Not that it matters, I suppose, since if not, the first instruction at address 0 could be a CDS.

**Comment by thewonderidiot** [comment]
Yep -- a real HOP instruction gets executed, with 000000000 as the HOP constant, so anything that gets set by a normal HOP gets set to 0. In the penultimate screenshot above, you can see that happen as the forced HOP instruction takes place: DM changes from 0-Duplex to 0-Simplex and DS changes from 13 to 0.

**Comment by thewonderidiot** [comment]
Another piece of evidence: the documentation for the PTC contains the _exact same sentence_, even though the same document contains the PTC ADAPT self-test code that proves otherwise: [pdf page 98](https://www.ibiblio.org/apollo/Documents/19730064346_1973064346.pdf).
![image](https://github.com/virtualagc/virtualagc/assets/94056/5683b16c-81eb-498a-9ad5-325b5cf2e772)

**Comment by rburkey2005** [comment]
Yes, I think somebody wrote up a confused description, and it just kept getting cut-and-pasted, though the cutting and pasting may have been more literal back then than it is now.  I can sympathize, since `HOP` is reasonably confusing to discuss in the best of times, let alone when the `HOP` is being virtually generated by the hardware.
