### ISSUE TITLE
ValueK seems not initialized in some CCS cases in agc_engine.c

### ISSUE THREAD

**Issue by spacex15** [virtualagc/virtualagc#1222]
<img width="558" alt="image" src="https://github.com/virtualagc/virtualagc/assets/7689189/973a79a3-b1a7-4dd7-a151-7c03a76951ea">

**Comment by rburkey2005** [comment]
I don't see it.  I see `ValueK` being initialized when `Address10 < REG16`, and I see `ValueK` being used when `Address10 < REG16`.

**Comment by spacex15** [comment]
you're right,

this compiler is just dumb
