### ISSUE TITLE
bug in virtualagc/yaYUL/GetOctOrDec.c

### ISSUE THREAD

**Issue by antoine-mathys** [virtualagc/virtualagc#1227]
GetOctOrDec() accepts "+" and "-" as octal values and "+D" and "-D" as decimal values. sscanf() doesn't set "Value" in these cases. If these are supposed to be valid inputs (an implicit 0 ?) this should be documented and "Value" should be set directly.
I can write a patch if you want.

**Comment by rburkey2005** [comment]
@antoine-mathys Thanks for catching that!  It now returns an error upon detecting that case.
