### ISSUE TITLE
Wrong link on website to syntax-highlighted Skylark source code

### ISSUE THREAD

**Issue by indy91** [virtualagc/virtualagc#1228]
Not sure if website issues are meant to be tracked here, but it seemed like a convenient place to make note of it.

On the Colossus page (https://www.ibiblio.org/apollo/Colossus.html) when I click the link for the "Syntax-highlighted, hyperlinked  HTML" source code of Skylark 48 then the link is:

https://www.ibiblio.org/apollo/listings/Artemis048/MAIN.agc.html

which gives a 404 message. Of course it needs to be Skylark048 instead of Artemis048.

**Comment by rburkey2005** [comment]
@indy91 What a great day it will be when the descendants of ChatGPT will write the website for me, and protect us all from my mistakes!  Of course, when that day comes, there likely will be no humans left who are interested in reading any of the material on the site, so it won't all be gravy.  :smile: 

Thanks!  Fixed.
