### ISSUE TITLE
yaYUL didn't assemble properly (binary didn't matchup)

### ISSUE THREAD

**Issue by Jackcybox007** [virtualagc/virtualagc#1233]
When I try to make a disassembler I find myself stuck with parity issues, parity is not in the same bit position sometimes it will be at bit 16, and then the next line parity is on bit 15 so I come up with an algorithm to detect the parity bit the discard it (make it 0).
Then I started to notice that the binary file that yaYUL outputs doesn't match the listing from yaYUL.
the listing says it should be octal 52011 (binary:  0101010000001001) 
then in the binary file is octal112011       (binary: 1001010000001001)
which moves 1 place up and it seems to be this specific octal (or the octal too but I didn't test it)

Is it just me or is the assembler the problem? Any help would be helpful. 
![swappy-20241208-160839](https://github.com/user-attachments/assets/72e306ed-94e2-4eee-93d2-0a1e8a6af0da)

**Comment by rburkey2005** [comment]
> When I try to make a disassembler I find myself stuck with parity issues, parity is not in the same bit position sometimes it will be at bit 16, and then the next line parity is on bit 15 so I come up with an algorithm to detect the parity bit the discard it (make it 0).
> Then I started to notice that the binary file that yaYUL outputs doesn't match the listing from yaYUL.
> the listing says it should be octal 52011 (binary: 0101010000001001)
> then in the binary file is octal112011 (binary: 1001010000001001)
> which moves 1 place up and it seems to be this specific octal (or the octal too but I didn't test it)

@Jackcybox007 The parity bit does _not_ move around, but its position _is_ confusing when the `--hardware` switch is used. 

Suppose the raw value obtained by assembling an opcode &mdash; which is what's printed in the assembly listing &mdash; is represented by the 15 bits
    `HLLLLLLLLLLLLLL`
And suppose the parity is P.  Then what the hardware sees (and what's in the binary file output by the assembler) is:
    `HPLLLLLLLLLLLLLL`
So in the example you've given, `HLLLLLLLLLLLLLL` is octal 52011, so
    `H` = 1
    `LLLLLLLLLLLLLL` = 01010000001001
    `P` = 0
The end result is thus:
    `HPLLLLLL LLLLLLLL` = 1 001 010 000 001 001 = octal 112011

**Comment by rburkey2005** [comment]
@Jackcybox007 I assume my explanation resolved your issue, so I'm closing this problem report.  If I'm assuming wrong, feel free to reopen it and provide whatever additional info is needed.
