### ISSUE TITLE
Transcribe Q,R-AXES JET SELECT AND FAILURE CONTROL LOGIC (pp. 554-568)

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#198]
Transcribe the scans for the Q,R-AXES JET SELECT AND FAILURE CONTROL LOGIC log section into [its source file](https://github.com/rburkey2005/virtualagc/blob/master/Sunburst120/Q_R-AXES_JET_SELECT_AND_FAILURE_CONTROL_LOGIC.agc). This section ranges from pages 554 to 568.

This section has no corresponding log sections in Luminary 099 or Aurora 12. It will have to be transcribed from scratch.

Reduced quality scans can be found [here](http://www.ibiblio.org/apollo/ScansForConversion/Sunburst120/). The original quality scans are available at [the Internet Archive page for BURST120](https://archive.org/details/yulsystemforagcr00nasa). Note that in both cases, the page numbers specified on this ticket are those printed on the original pages, not those in the filenames. The numbers will be close, though, so you should be able to find them pretty quickly. The start of the log section should be fairly obvious.

**Comment by 7ofNine** [comment]
I' ll take this one
