### ISSUE TITLE
Transcribe ORBITAL INTEGRATION PROGRAM (pp. 776-798)

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#218]
Transcribe the scans for the ORBITAL INTEGRATION PROGRAM log section into [its source file](https://github.com/rburkey2005/virtualagc/blob/master/Sunburst120/ORBITAL_INTEGRATION_PROGRAM.agc). This section ranges from pages 776 to 798.

This section has [a corresponding log section in Luminary 099](https://github.com/rburkey2005/virtualagc/blob/master/Luminary099/ORBITAL_INTEGRATION.agc), though of a slightly different name. The two may be similar. I recommend starting from that, and looking for any changes in the Sunburst scans.

Reduced quality scans can be found [here](http://www.ibiblio.org/apollo/ScansForConversion/Sunburst120/). The original quality scans are available at [the Internet Archive page for BURST120](https://archive.org/details/yulsystemforagcr00nasa). Note that in both cases, the page numbers specified on this ticket are those printed on the original pages, not those in the filenames. The numbers will be close, though, so you should be able to find them pretty quickly. The start of the log section should be fairly obvious.

**Comment by 7ofNine** [comment]
I'll take this one
