### ISSUE TITLE
Transcribe 206 SERVICE ROUTINES (pp. 815-831)

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#221]
Transcribe the scans for the 206 SERVICE ROUTINES log section into [its source file](https://github.com/rburkey2005/virtualagc/blob/master/Sunburst120/206_SERVICE_ROUTINES.agc). This section ranges from pages 815 to 831.

This section has no corresponding log sections in Luminary 099 or Aurora 12. It will have to be transcribed from scratch. The printer had a lot of trouble with this section, unfortunately. Things are pretty messed up from between pages 820 and 830, and 12 words are missing entirely off the bottom of page 828. There's a corresponding section in SHEPATIN [(which still needs a sponsor)](https://rburkey2005.github.io/virtualagc/volunteer.html), but it may or may not have an identical copy of these words. Don Eyles will be sending us some snapshots of the relevant pages soon, so we can take a look at them.

In the mean time, I've performed a preliminary disassembly of the words from the octal listing that can be used:
```
30,2450     50070   INDEX   RUPTREG1
30,2451     55010   TS      RN
30,2452     10070   CCS     RUPTREG1
30,2453     12445   TCF     VPATLOOP
30,2454     00006   EXTEND
30,2455     31777   DCA     TIGNTION
30,2456     53327   DXCH    STATIME
30,2457     30071   CA      RUPTREG2
30,2460     54003   TS      EBANK
30,2461     00003   RELINT
30,2462     06112   TC      INTPRET
30,2463     45175   VLOAD   LXA,2
```

Reduced quality scans can be found [here](http://www.ibiblio.org/apollo/ScansForConversion/Sunburst120/). The original quality scans are available at [the Internet Archive page for BURST120](https://archive.org/details/yulsystemforagcr00nasa). Note that in both cases, the page numbers specified on this ticket are those printed on the original pages, not those in the filenames. The numbers will be close, though, so you should be able to find them pretty quickly. The start of the log section should be fairly obvious.

**Comment by thewonderidiot** [comment]
I'll try my hand at at this section next.

**Comment by thewonderidiot** [comment]
@rburkey2005, heads up. The line number jump you saw from one page to the next is a real problem, at least in this section. The first instance of it I came across was indeed a total failure on the part of the printer to print an instruction. It's pretty obvious on the "original" images available from archive.org that this isn't a case of something missed in scanning, but rather the printer screwing the pooch.

Do you remember if you saw this in any other sections, or just this one?

**Comment by rburkey2005** [comment]
I only looked at the small area where it was obviously messed up.

**Comment by rburkey2005** [comment]
However, this is where the rubber meets the road, where the guts meet the glory, where it becomes reconstruction rather than mere transcription, where not just anybody can do it.  In short, an opportunity for heroics rather than a disaster! What's not to like?

**Comment by thewonderidiot** [comment]
Hahaha, indeed! Right now I'm just finding myself wishing the main symbol table was sorted by address rather than alphabetically... or, rather, it would be fantastic if it was printed both ways.

I just went back through the first page that I mentioned and combed through the addresses. There were _two other lines_ in the middle of the page that were just totally missing! I guess it's nice that it didn't affect the gigantic documentation comment that precedes this page, but it is a bit unfortunate that we're obviously missing comments on some of these lines. there was a half-comment I transcribed a bit earlier that makes a LOT more sense now that I see there's a line missing after it. The first half of the comment did give me the name of the symbol I needed for the next line though!

**Comment by thewonderidiot** [comment]
Make that three, jeez.

**Comment by rburkey2005** [comment]
I hope you're nicely commenting them with ### notes.

**Comment by thewonderidiot** [comment]
Yup, there'll be a lot of those.

I ended up stuck on a data word, with no idea what its label was or what directive was used to assemble it. So I went ahead and made that symbol table for bank 30 sorted by address. For future reference:
```
30,xxxx symbols
---------------
30,2000 PREREAD
30,2011 BIBIBIAS
30,2047 READACCS
30,2060 WASFILT
30,2064 PIPREAD
30,2065 PIPSDONE
30,2070 REDO5.31
30,2072 CHEKAVEG
30,2102 MAKESERV
30,2114 PIP2CADR
30,2116 AVEGOUT
30,2121 SLIPONE
30,2124 AVOUTADR
30,2125 FILTAD
30,2126 GTSAD
30,2127 5.31SET
30,2131 5.6SET
30,2133 SERVICER
30,2134 PIPCHECK
30,2150 PIPLOOP
30,2161 GOMASS
30,2173 COPYCYCL
30,2230 CHGPHASE
30,2237 PGNCSMON
30,2233 -MAXDELV
30,2234 PLUSXDVA
30,2235 200DEC
20,2236 PLUSXDVD
30,2251 AVERAGEG ( == AGSMON)
30,2256 THRUSTLO
30,2260 NODV
30,2270 DVEXIT
30,2273 BOOSTMON
30,2313 DVMNKILL
30,2315 AVEGADDR
30,2316 THRSHLD+
30,2317 ENGNFAIL (arrow pointing to it)
30,2324 SERVEXIT
30,2327 GIMBLMON
30,2351 GIMBLON
30,2357 GIMBLOFF
30,2365 GTHSHLD
30,2366 AVGEND
30,2410 AVEMIDAD
30,2414 NORMLIZE
30,2436 VPATCHER
30,2445 VPATLOOP
30,2470 TUMTASK
30,2477 TMTSK
30,2542 EOTUM
30,2545 1SECTM
30,2546 CRIT
30,2547 RESET
30,2574 PIPASR
30,2612 REPIP1
30,2620 REPIP3
30,2623 DODELVZ
30,2624 REPIP4
30,2633 REREADAC
30,2663 CHKTEMX
30,2676 DONEADR
30,2677 2/PI
30,2701 LIMOMG
30,2703 FINDCDUD
30,2744 AXISFILT
30,2774 ROTANGLE
30,3020 SMCDURES
30,3064 SINCOSCD
30,3070 REPEAT1
30,3103 CALCGRAV
30,3137 CALCRVG
30,3162 KP1P
30,3164 KP1P1
30,3166 DP1/BTH
30,3170 DP1/10
30,3172 J(RE)SQ
30,3174 -MUDT
30,3176 2SEC(17)
30,3200 DP2(-3)
30,3202 MUEARTH
30,3204 MUMOON
30,3206 MASSMON
30,3231 CHOICE1
30,3241 CHOICE2
30,3247 VEXFINDA
30,3252 MININIT
30,3256 VEXFINDD
30,3263 VEXLOOP
30,3351 ENDVEX
30,3373 NOMASS
30,3377 2SEC(9)
30,3401 LOWFCRIT
30,3402 MASSCRIT
30,3403 RCSVEX
30,3405 APSVEX
30,3407 CVEX1
30,3410 CVEX2
30,3411 CVEX3
30,3412 CVEX4
30,3413 CVEX5
30,3414 MINMASSA  (== FSTEP)
30,3415 SLOPE
30,3416 MINMASSD  (== VEXSTEP)
30,3420 FSTEP1
30,3421 SLOPE1
30,3422 VXSTEP1
30,3424 FSETP2
30,3425 SLOPE2
20,3426 VXSTEP2
30,3430 FSTEP3
30,3431 SLOPE3
30,3432 VXSTEP3
30,3434 FSTEP4
30,3435 SLOPE4
30,3436 VXSTEP4
30,3440 HIFSTEP
30,3441 HISLOPE
30,3444 ETHROTL
30,3445 MASSMULT
30,3456 PCNTOVER
30,3564 THROTDT
30,3465 PGUID
30,3466 PCNTFMAX
30,3476 THROTCON
30,3505 AWAY
30,3507 PCNTJOB
30,3533 SCALEFAC
30,3535 2.PG.FRT
30,3537 +FLOW
30,3536 -LOCRIT     (== FEXTRA)
30,3540 ACCLJOB
30,3547 FOLDCALC
30,3567 IS-IT-ON
30,3556 FCOMPSET
30,3577 WHERETO
30,3613 FLATOUT
30,3620 DOPIF
30,3632 DAPLRETN
30,3634 DOIT
30,3677 +FODD
30,3700 -FMAX
30,3702 +FHIGH
30,3704 +HICRIT
30,3705 THROTOVR
30,3713 DAPLOGIC
30,3750 JETSET
30,3770 HITHRESH
```

**Comment by thewonderidiot** [comment]
Uuuuughh, and those places where two lines were printed on top of each other aren't necessarily just two. I'm currently on a spot where the printer put 10 instructions on 2 lines.

**Comment by thewonderidiot** [comment]
@rburkey2005 @jimlawton @ohommes Despite the unfortunate print quality of this section, I think it also represents a neat piece of history. The green arrow on [page 824](http://www.ibiblio.org/apollo/ScansForConversion/Sunburst120/Sunburst120-0824.jpg) is pointing at a program alarm, described in the comment as "Engine on but no thrust". Given what I've read about the computer troubles on Apollo 5, this looks like exactly the alarm that would have happened. And looking at this and all the other stuff written in this section, it looks like this listing was likely used to debug the issue! How cool is that? :)

**Comment by thewonderidiot** [comment]
Well, that was fun! And challenging. Here is the full list of disassembled instructions the printer missed or messed up:
```
30,2015 55511           TS       DVCNTR
-------------
30,2040 32235           CAF      200DEC
-------------
30,2044 04161           TC       PHASCHNG
-------------
30,2046 15727           TCF      TASKOVER
-------------
30,2123 12064           TCF      PIPREAD
30,2124 02366 AVOUTADR  GENADR   AVGEND
30,2125 02015 FILTAD    GENADR   FILTER
30,2126 02572 GTSAD     GENADR   GTS
-------------
30,2137 10403           CCS      DELVX
30,2140 02142           TC       +2
30,2141 02150           TC       PIPLOOP
30,2142 62233           AD       -MAXDELV
30,2143 00006           EXTEND
30,2144 62150           BZMF     PIPLOOP
30,2145 04755           TC       ALARM
30,2146 00205           OCT      00205
30,2147 12152           TCF      +3
30,2150 11512 PIPLOOP   CCS      PIPCTR
-------------
30,2230 00006           EXTEND
-------------
30,2243 42234           CS       PLUSXDVA
30,2244 61534           AD       ABDELV
30,2245 00006           EXTEND
30,2246 62256           BZMF     THRUSTLO
30,2247 31341           CA       SETDVCNT
30,2250 55511           TS       DVCNTR
-------------
30,2252 10035           OCT      10035
-------------
30,2262 10000           CCS      A
-------------
30,2305 07022           OCT      07022
-------------
30,2337 62357           BZMF     GIMBLOFF
-------------
30,2350 12357           BZF      GIMBLOFF
-------------
30,2356 12237           TCF      PGNCSMON
-------------
30,2362 26077           ADS      DAPBOOLS
30,2363 00003           RELINT
30,2364 12237           TCF      PGNCSMON
30,2365 00074 GTHRSHLD  DEC      60
-------------
30,2367 54765           TS       OLDBT1
-------------
30,2377 37756           CA       BIT6
-------------
30,2415 50070           INDEX    RUPTREG1
30,2416 31514           CA       RAVEGON
30,2417 50070           INDEX    RUPTREG1
30,2420 55010           TS       RN
30,2421 10070           CCS      RUPTREG1
30,2422 12414           TCF      NORMLIZE  +2
-------------
30,2424 31511           DCA      TAVEGON
30,2425 53327           DXCH     STATIME
30,2426 00003           RELINT
30,2427 06112           TC       INTPRET
30,2430 45175           VLOAD    CALL
-------------
30,2434 77776           EXIT
30,2435 15567           TCF      ENDOFJOB
-------------
30,2453 12445           TCF      VPATLOOP
30,2454 00006           EXTEND
```

**Comment by rburkey2005** [comment]
So ... do you feel a nice sense of accomplishment?

I recall having to do that, though in my case it was for fewer missing lines, _but_ from a printout that was so messed up that even some of the corresponding octals were completely gone.  When (a long time later) I got better copies of the missing data, it was both a great rush to find out that I had been exactly correct, but also a let-down in which I said to myself, "why did I waste all this effort!"  And so it goes.  :-)

Great job!

**Comment by thewonderidiot** [comment]
Thanks! :)

That's impressive! Did it take some fiddling to get the banksums to come out right?

I don't know what I would have done without the octals and symbol table here. It's too different from anything else we have.

**Comment by rburkey2005** [comment]
Well, in my case, it was really a question of trial and error, of inserting source code that I thought made sense, and then if the checksums didn't work, trying other source code. And honestly, it was just a couple of places where one instruction was missing, so it wasn't all that clever. But even so, the checksums aren't all that good an indicator of correctness, so it was a gamble. I was pretty proud of myself anyway. :-)
