### ISSUE TITLE
Transcribe PREBURN FOR APS2 (pp. 911-912)

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#231]
Transcribe the scans for the PREBURN FOR APS2 log section into [its source file](https://github.com/rburkey2005/virtualagc/blob/master/Sunburst120/PREBURN_FOR_APS2.agc). This section ranges from pages 911 to 912.

This section has no corresponding log sections in Luminary 099 or Aurora 12. It will have to be transcribed from scratch.

Reduced quality scans can be found [here](http://www.ibiblio.org/apollo/ScansForConversion/Sunburst120/). The original quality scans are available at [the Internet Archive page for BURST120](https://archive.org/details/yulsystemforagcr00nasa). Note that in both cases, the page numbers specified on this ticket are those printed on the original pages, not those in the filenames. The numbers will be close, though, so you should be able to find them pretty quickly. The start of the log section should be fairly obvious.

**Comment by 7ofNine** [comment]
I'll take this one
