### ISSUE TITLE
yaDSKY2 has wrong default value for --port

### ISSUE THREAD

**Issue by rburkey2005** [virtualagc/virtualagc#246]
The default value for --port in yaDSKY2 is actually 19797 rather than the documented 19697.  The latter is also the default value for yaAGC, so the intention was that if you ran both yaAGC and yaDSKY2 without a --port setting, they would connect.  However, they do not, since the default in yaDSKY2 is wrong.

The [website's developer info page](https://rburkey2005.github.io/virtualagc/developer.html#Using_LM_Hardware-Simulation_Programs) suggests using the range 19697+ for CM and 19797+ for LM, with the intention of being able to run a CM and LM simulation simultaneously without having their port ranges overlap, which is perhaps how this default got set wrong in the first place.

@ohommes @jimlawton This is easy enough to fix in yaDSKY2, but it has apparently _always_ been wrong, so the question arises as to whether it's better to fix yaDSKY2 or just to change the documentation.  Personally, I'd rather do the former, but at this point it may be better to do the latter, to avoid breakage.  It doesn't affect something like VirtualAGC, which always uses the --port switch explicitly anyway.  

Opinions? I'll wait until (say) the 20th before fixing it, unless there are overwhelmingly strong reactions one way or the other in the meantime.

**Comment by ohommes** [comment]
I vote fix yaDSKY2! So Without --port it should use its defaults.

**Comment by rburkey2005** [comment]
@ohommes You're the only one who voted, so you win!
