### ISSUE TITLE
Transcribe ABSOLUTE ADDRESSES FOR UPDATE PROGRAM (p. 1)

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#281]
Transcribe the scan for the ABSOLUTE ADDRESSES FOR UPDATE PROGRAM log section into its source file. This section constitutes page 1.

This section a corresponding log section in Artemis 072, from which it has been populated. Look for differences and make corrections to the Luminary 210 version.

Reduced quality scans can be found [here](http://www.ibiblio.org/apollo/ScansForConversion/Luminary210/). The original quality scans are available at [the Internet Archive page for Luminary 210](https://archive.org/details/luminary21000miti). Note that the page numbers specified on this issue correspond to those printed on the original pages, not necessarily those in the filenames of the archive.org images. Look for the start of the log section; it should be marked with a "user's page no. 1".

**Comment by tgmaxx** [comment]
Hi Mike,
Do you have a standard for how you want the text formatted? Use of tabs, spaces, etc.. And, what file type/format do you require?
Thanks,
Tom

**Comment by thewonderidiot** [comment]
@tgmaxx, not sure if you removed your comment or some glitch is preventing me from seeing it -- but I just finished making the Luminary 210 page describing all of that at https://github.com/virtualagc/virtualagc/wiki/Luminary-210-Transcription. Let me know if you have any questions not answered there. :)

This section is somewhat of a special snowflake -- it's not present in any previous listings and, while most of the lines aren't marked as coming from remark cards, they also don't appear to contain any code. Until we figure out otherwise, it's probably best to treat this entire section as comments.

**Comment by brf1** [comment]
I am interested in volunteering to help transcribe.

**Comment by thewonderidiot** [comment]
Cool, thanks @brf1!
