### ISSUE TITLE
Proof comments using octopus/ProoferComments

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#442]
Or some advanced new tools that supersede them. :)

**Comment by rburkey2005** [comment]
I guess I've already said I'd do this, though I should at least finish writing the wiki article I've started about the method, so see if anybody else gets so excited about it they want to jump on it.

**Comment by rburkey2005** [comment]
Oops!  Finished this a long time ago and forgot to close the issue!
