### ISSUE TITLE
Design/Documentation/Usage discrepancy in ##- and ###-style comments

### ISSUE THREAD

**Issue by rburkey2005** [virtualagc/virtualagc#571]
There are multiple discrepancies between the way ##-style and ###-style comments are documented and used in practice, as well as design discrepancies between how they are treated in plain vs. HTML assembly-listings.  These problems have been exacerbated lately by the bulk changeover to ##-style (as opposed to #-style) for all "modern" comments (as opposed to comments in the original AGC source), as well as by the large number of corrections I've been making in proofing comment text in Aurora, Sunburst, Comanche, and Luminaries 99 and 210 using [octopus/ProoferComments](https://github.com/virtualagc/virtualagc/wiki/Verifying-Correctness-of-Comment-Text-in-AGC-Source-Code-Files).

At any rate, rather than describe all of these problems in detail here, I'll describe a proposed scheme for how I think they should work in the future.  This description is consistent with the corrections I've been making with octopus/ProoferComments, but require yaYUL changes to overcome the mentioned design defects.  I'm going to assign this to myself, unless somebody else wants to take it over from me, but not actually make any such changes for a month or so, to allow time for reactions to accumulate here.

With that said, the principal difficulty is the usage of ##-style comments in such a way that they produce the intended visual appearance _both_ in HTML and ASCII assembly-listings created by yaYUL.

<blockquote><b>Note:</b> There is an additional design problem, not presently covered by this proposal, which relates to the feature of the original AGC comments that YUL handled but yaYUL does not, namely the A-style comments.  yaYUL treats R-style and A-style comments identically, as full-line comments.  YUL, on the other hand, treats A-style comments as being "aligned with the code", which I didn't know at the time I designed the .agc file format.  This columnar alignment is something that YUL could handle easily because the input- and output-formats were strictly column-based, and never changed.  As it turned out, yaYUL input is not column-based in any meaningful sense, and several output assembly-listing formats (HTML and ASCII among them, plus a source-reformatting-only option) are supported that have mutually-incompatible columnar alignment.  I don't presently envisage any meaningful way for yaYUL to manage columnar alignment with A-style comments (which aren't marked in any special way in .agc files in any case), but if anybody has an idea as to how to extend yaYUL support to A-style comments, addition of that support might be handled as part of the same set of yaYUL ##/### changes mainly targeted by this problem report.  I presume at the very least that it would involve a new comment type, perhaps using '|' in column 1 rather than '#'.  Of course, at present, white-space usage in .agc file comments is presently often (usually) not closely-related to that in the original A-comments anyway, so any new such comment type would not be very valuable until that situation was corrected as well.</blockquote>

Proposed ongoing usage:

* #-style comments:  Used only for verbatim, upper-case comments from the original AGC code, handled precisely as at present.
* ##-style comments:  Used for any "modern" comments, corrections, annotations, etc. on a line-by-line basis.  They should appear _only_ in column 1 (not as end-of-line comments).  While primarily textual, they accept HTML markup in a limited way, and are inserted verbatim into their associated comment-boxes in the HTML assembly listings produced by "yaYUL --html", which means that by default consecutive ##-comments form a single continuous flow of text, which can only be overcome by insertion of HTML markup like \<br> or \<pre>, and inserted spaces or tabs are of no use in effecting columnar alignment; moreover HTML entities such as \&mdash; are allowed.  However, in the plain-ASCII assembly listings, they will not form a continuous flow of text, but will retain their white space and their breakup line-by-line, and will be processed in such a way as to remove all \<tags>, and a TBD selection of HTML entities (specifically \&mdash;) are replaced by plain-ASCII equivalents.
* ###-style comments:  Used only as the first line of each .agc file to indicate the standard HTML include-file, the contents of which file being inserted as-is into HTML assembly listings, while the entire ###-comment is simply omitted from ASCII assembly listings.

**Comment by thewonderidiot** [comment]
Slow reply.... but this sounds good to me. The only thing I wonder is if it might make sense to insert implicit `<br/>`s at the end of ## lines... but I could see that potentially making the text look weird in the HTML versions.

**Comment by rburkey2005** [comment]
Okay, nobody has expressed any other ideas in a long time, and I've been de facto enforcing this throughout all of the comment-text proofing I've been doing (which is now complete), so I'll assume this is the way it will work from now on.
