### ISSUE TITLE
Certain fixes to AGC comment text have a tendency to be incorrect

### ISSUE THREAD

**Issue by rburkey2005** [virtualagc/virtualagc#572]
# The Problem

I have recently been proofing and correcting comment text in AGC source-code files using the [octopus/ProoferComments](https://github.com/virtualagc/virtualagc/wiki/Verifying-Correctness-of-Comment-Text-in-AGC-Source-Code-Files), but a small percentage of those fixes have tended to break already-correct comments in a systematic way, by removing certain characters which were actually supposed to be present.

The scenario in which the problem occurs is best illustrated by comments which serve as documentation of the functionality of a log section, a program, or a subroutine, as in this slightly-edited excerpt from Luminary210/P51-53.agc:

<pre>
# PROGRAM NAME- PROG52          DATE- JAN 9, 1967
# MOD NO- 0                     LOG SECTION- P51-P53
# MODIFICATION BY- LONSKE       ASSEMBLY- SUNDANCE REV 46

# FUNCTIONAL DESCRIPTION-

#      ALIGNS THE IMU TO ...
</pre>

In this example, heading names are followed by a '-' character, though in other cases they may alternatively be followed by '\_' or ':', depending on the whims of the original developer, I suppose.

The _problem_ is that naively proofing using octopus/ProoferComments has a fairly high probability of _removing_ the '-', '\_', or ':' character during the proofing process.  I do not have statistics, but for the sake of argument let's suppose that the probability of this false removal is 25%.  Furthermore, the nature of the proofing process is such that additional proofing passes using octopus/ProoferComments cannot detect the error and restore the now-missing '-', '\_', or ':'.

The cause of this problem is that it is octopus itself removes these characters from the proofing images created by ProoferComments, so from the proofing images, the absence of these characters seems perfectly correct ... it is only by consulting the original scans that the truth can be determined.  And while this consultation with the original scans is feasible (though time-consuming) in the initial proofing pass with octopus/ProoferComments, in subsequent proofing passes there is nothing whatever which would prompt someone to make such a check!

The AGC versions directly affected are:

* Aurora 12
* Sunburst 120
* Luminary 99
* Comanche 55
* First 600 pages of Luminary 210.  (After about p. 600, I recognized the nature of the problem and began actively trying to avoid it.)

The following AGC versions are indirectly affected, since their transcription is based on cut-and-paste from Aurora 12 and Luminary 99:

* Retread 44
* Luminary 69

# Proofing with octopus/ProoferComments, Going Forward

The best thing would be for octopus to be fixed so that it either does not do this, or else has a much-reduced probability of doing so.  I was under the impression that this removal &mdash; and the somewhat-similar problem of arbitrary removal of '=' characters &mdash; was a side-effect of the process of removal of image backgrounds (green-and-white bars or black horizontal rules on white paper), but it is not:  "octopus --comments" exhibits the problem, but "octopus --no-crop" does not.  Therefore, it is an artifact of the cropping process ... though I have personally not been able to figure out how it occurs.

Lacking a fix to "octopus --comments", the only strategies for correct proofing seem to be:

* Check the original scans every time the correction may be removal of one of the problematic characters, and to edit them back into the imagery produced by octopus if the character is supposed to be present ... a very time-consuming process, relative to normal proofing.  Or,
* Generate all proofing images by manually editing "octopus --no-crop" imagery rather than relying on "octopus --comments" imagery.  

The latter is, of course, the safer alternative.  But since it is far more time-consuming &mdash; I think &mdash; I am going to personally stick with the former.

# Restoral of the '-', '\_', ':' Characters _Already_ Removed by the Proofing Process

In order to restore the now-missing problematic characters, it is necessary to know where the problem occurs, and additional proofing passes with octopus/ProoferComments (as octopus presently operates) cannot achieve that.  It seems to me that there are three possible means of addressing the problem:

1. If octopus were fixed, then it would be possible to generate all-new proofing imagery, and perform a new proofing pass (which would hopefully be much, much quicker than the original proofing).  One area of caution would be that since octopus is not perfect in many respects, a high percentage of images created by octopus have _already_ been manually edited, and it is important _not_ to regenerate those images and thus lose all of the time-consuming manual editing that has been performed.  (Only a very tiny proportion of the manually-edited pages would exhibit the problem described in this problem report anyway, since they are mainly, though not entirely, derived from "octopus --no-crop" images rather than "octopus --comments" images.)  Thus, rather than straighforwardly generate all-new octopus images, it would be necessary to do so _only_ for images not already manually edited.
2. The locations of all removals of '-', '\_', or ':' characters could be extracted from the git logs, and each of those occurrences could be examined manually.  It would be necessary not only to restore the missing characters into the .agc files, but also to edit the still-exiting octopus imagery, so that future runs of ProoferComments didn't revert back to the problem.
3. To a limited extent, cross-comparisons of different AGC versions can detect the problem, since it likely does not occur at the same places in every image set.  On the other hand, if the problem was inherited by cut-and-paste (such as Aurora-Retread or Luminary 99-69), cross-checking is of no help.
4. Simply ignore the problem.  The problematic scenario mentioned only occurs a tiny percentage of the time &mdash; i.e., the number of errors introduced is far, far less than the number corrected &mdash; and besides, many time there isn't supposed to be '-', '\_', or ':' character in that situation anyway, since in many cases the developer actually _didn't_ use such a character; thus, the absence of the character, while incorrect with respect to the original printout, is neither weird nor abnormal.

Since it is simpler, the latter is what I personally intend to do for now, until a more-effective strategy can be implemented.

**Comment by rburkey2005** [comment]
@thewonderidiot Just calling your attention to this, and not expecting any instant fix!

**Comment by rburkey2005** [comment]
I've coopted some machinery in ProoferComments which provided a visual indication of possible missing '=' characters, so that it also visually indicated some possible missing '-', '\_', and ':' characters.  Which on an ongoing basis at least helps in avoiding some editing of graphical imagery, but doesn't prevent having to consult the original scans, isn't a fix, and doesn't help in fixing the errors which have already been introduced.

**Comment by thewonderidiot** [comment]
Hrrrm, strange that it's happening in --comments but not --no-crop. I would have thought to blame the despeckler at first. But given that, it must be the logic that tries to sort contours between lines of text. Would I be right in guessing that this usually happens on full-line comments that are followed by blank lines (not blank comments) or code?

I think I'm going to need to bite the bullet and just co-opt your approach of calling out to Tesseract and determining line assignments that way. It's proven itself to be pretty good at figuring out what characters are on what line... and I'm pretty sure Retread's snaggleprinter would destroy --comments as it's currently written.

**Comment by rburkey2005** [comment]
It's hard to say.  This proofing activity occurs very much in my own short-term memory, so I know little other than that it has probably happened 100+ times, but not on a majority of possible opportunities.  It's possible that that scenario is as you say, but I'd have to extract the instances from the git log and analyze it somehow to find out.

It took me quite a while to get the notion that the line-removal was doing it, and to realize that --no-crop _always_ produces the correct results, as far as I can tell.  Any time I have problems with --comments, I can always fall back on --no-crop, and --no-crop never disappoints me by doing anything I think of as weird or unexpected.

The next few I see, I'll try to see the pattern, if any.

**Comment by thewonderidiot** [comment]
Okay, cool. I'll get to work on a re-implementation of --comments. I should be able to have something for you some time in the next few days, hopefully.

**Comment by rburkey2005** [comment]
There's no great rush. I'll be finished with Luminary 210 today or tomorrow, so I won't need it again until the Retread our the next Luminary is ready. Unless I try to work on Solarium, I guess.

**Comment by thewonderidiot** [comment]
Actually, I was wrong. It turns out it was my attempt at filtering out noise that was filtering out stuff a bit too big. I've shrunk that down, now, and some missing dashes are coming through.

Also, Retread should be completely done, minus comment proofing. Though as I mentioned, it's possible that octopus will make a mess of it.

**Comment by jimlawton** [comment]
Ron, I'm very suspicious of underscores. The H1800 printer didn't have an underscore character as fas as I can determine (Table I, Page 167 of the Prog. Ref. Man.). In YUL, I have found that what look at first glance like underscores turn out to actually be dashes. You can spot it by noticing that letters in the same column are all shifted down, indicating that the head alignment for that column of Snaggleprinter was off. 

Also, w.r.t. ":", my hypothesis there is that the programmers put "-", but the particular assembly listing got printed on a printer that printed colon for that character. E.g. card code 8,4 in Table I prints as minus on the standard printer, but as colon on the high-speed printer. 

I'm not saying there were no underscores or colons in the original AGC source, I'm just very suspicious. 

The proofer might actually be doing the right thing in some cases...

**Comment by rburkey2005** [comment]
@thewonderidiot Oh, I hadn't been paying attention, so I didn't know Retread was ready.  I'll look at it next.

By the way, about "my" approach for determining the lines from Tesseract itself, it doesn't always work, because Tesseract sometimes outputs the characters out of the order my code expects, which messes it up significantly.  That's okay for ProoferComments, because I can just edit the files output by octopus on those relatively-rare occasions.  (I just move the lines apart a little vertically.)  I'm not sure that's a good approach for octopus itself, though, because when it fails I'm not sure about getting the same effect by editing the scanned imagery input to octopus.  So there might be no recourse at all if it messed up.

@jimlawton Yes, it's puzzling.  Perhaps they were able to replace part of the printing assembly to get different character sets, or had more printers than we know about.  There are certainly characters appearing in these printouts that aren't supposed to exist in the character set supported by YUL.  But it's clear on Luminary 210, for example, that there are really underscores, because their geometry is different from hyphens:  the underscores have consistent positioning and are consistently wider than the hyphens appearing in the same printout.  

I do grant that in some of the other printouts the snaggling does move some of the dashes very low, and it becomes a matter of opinion just what they are; personally, I've usually interpreted them hyphens whenever I could reasonably get away with it.  I also grant that the system, as opposed to the coders themselves, may have been freely substituting characters.

Perhaps it's a question for Hugh.  Maybe when we get around to cross-checking between different program versions we could identify a case where every instance of some particular character has consistently been replaced by some other character.

**Comment by rburkey2005** [comment]
In fact, it's clear that they were able to use different printers, because [the copy of Colossus 249 I got from Fred Martin](http://www.ibiblio.org/apollo/ScansForConversion/Colossus249-Martin/) is on U.S. Letter or A4 size paper in portrait mode, and has an obviously different font.  There's no way it's a xerox of one of these big landscape printouts; it must have been printed out directly in that form.

**Comment by rburkey2005** [comment]
On the other hand, there's an example right in front of me of a character substitution which must have been done on the input side rather than by the printer.  I'm looking at Luminary 210, TJET LAW, where all the '?' characters appear as '|' on p. 1461.  Yet the printer was certain able to print question marks, since there some on p. 1460.

**Comment by jimlawton** [comment]
My nightmare: the IBM 360s running GAP supported different character sets than the Honeywells running YUL, and they changed the AGC source gradually after they had switched over to GAP...

I wonder do we have any idea when they stopped manufacturing ropes from YUL and started using GAP?

**Comment by thewonderidiot** [comment]
@rburkey2005  @jimlawton I was thinking the same thing while transcribing Sunburst, because the hyphens all seemed to be sort of vertically midway between a hyphen and underscore. In the end I just made everything hyphens in the sections I transcribed.

I did a bit of research into it and  the Wikipedia page on the underscore says IBM introduced it at the same time as the IBM 360, so GAP would have added support for it by that nature.

**Comment by thewonderidiot** [comment]
Ah, you beat me to it. I know one of the R-700 volumes mentions when they got their 360, so that would give a rough time frame at least. But it may also have been a function of rope; GAP may have been around during the later days of Sunburst, for example, but they probably would have stuck with YUL rather than try to convert card types. Likewise, it's possible Luminary Rev 1 was already GAP and never built with YUL.

**Comment by thewonderidiot** [comment]
So the IBM 360 was delivered in October 1966, and then for the next ten months underwent bringup and saw system/simulation software development. It became fully operational for general use in September 1967 -- a few months before Sunburst 120 was printed. So I'd say it's a toss-up if Sundance was built with Yul or GAP.

For what it's worth, I've looked at all instances of underscores in Luminaries 99 and 210, and not a single one corresponded with anything in Sunburst 120. They were all in new stuff.

**Comment by jimlawton** [comment]
Argghhh. So that means in all likelihood YUL will/was never be/- able to assemble some/all of the later post-transition images, i.e. most of the actual manned flights?

That is somewhat disappointing given my current obsession.

**Comment by rburkey2005** [comment]
I'm not sure that follows. At least in so far as character sets are concerned.

**Comment by jimlawton** [comment]
If later versions of the flight code used characters that didn't exist in the character set supported on the Honeywells, then how could YUL have ever been used to assemble those versions?

**Comment by rburkey2005** [comment]
Well, unless there literally were not enough bits in the encoding to encode the character at all, illegal characters are undoubtedly encoded as _some_ sequence of bits.  And unless those illegal sequences are explicitly checked for and rejected by the code, it's entirely possible that they might pass all the way through the processing and pop out at the other end unharmed ... particularly if they mainly occur in the comments, which you'd have to suppose would only be minimally processed.

Certainly, at the software design stage, I'll often make pronouncements about stuff that the input isn't allowed to have in it, only to later find that that stuff was appearing in the input after all, and was being processed just fine because I had been too lazy to explicitly check for it.  You can particularly imagine that happening if the pronouncements about the legal character set were based on a knowledge of the input devices, rather than being a particular desire of the programmers.  For example, you might say that '_' is illegal simply because you know that the card punch or card reader doesn't support '_', but not because of any particular design requirement of the software.

Of course, there are plenty of other scenerios too, where the whole thing might blow up!  I certainly wouldn't bet _money_ that it will work.  In fact, you may recall that the danger of it not working was one of the arguments I gave for making Retread your first test case, as opposed to Luminary 210.  I'm just saying that, a priori, it's not obvious to me that YUL can't process the illegal character, regardless of the words they chose to write down about it.

**Comment by rburkey2005** [comment]
For that matter, as long as the total number of unique characters was within the supported limit, we could handle it by having a preprocessor translate illegal characters to legal ones, then run YUL, then post-process to undo the character translation in the output assembly listing and whatever other output products there might be.  Perhaps not as simply done as said, but likely doable.

**Comment by rburkey2005** [comment]
And even _if_ there were too many unique characters being used, we could re-encode illegal 2-character combinations as legal 2-character ones, because I'd venture to say that it's highly unlikely that the number of _used_ 2-character combinations exceeds the potential number of legal 2-character combinations.

Or we could detect any word that uses an illegal character and replace it with some unused word consisting entirely of legal characters.

Or some other illegal-to-legal encoding scheme.  Since I've just thought of three of them, there are probably lots of possibilities.

**Comment by jimlawton** [comment]
@rburkey2005 I wasn't saying it wasn't possible, I was expressing my sorrow that it indicates that YUL itself may not have been used beyond late 1967, and that many of the actual flight ropes may have been manufactured by a program about which we know almost nothing...

Ho hum.

**Comment by rburkey2005** [comment]
Ah! I misinterpreted.

**Comment by thewonderidiot** [comment]
Sorry Jim, I didn't mean to rain on your parade! I suspect other than the underscore encoding and historical application, they're completely compatible. I had been thinking that the COUNT* directive was a GAP-ism, but I can see in the Pass 1s you've transcribed that Yul supports it as well, despite the fact that none of the four listings we have built by it make use of them. That's the only other thing I can think of that's seemed different between the two.

**Comment by jimlawton** [comment]
It's OK Mike, I'm used to rain :-).

**Comment by rburkey2005** [comment]
Having gone through a lot of pretty intensive cross-version AGC diffs over the last couple of months, involving all of the flown, manned missions directly, I can say that while I did end up fixing a handful of problem like the one in the issue description, it's no longer reasonable in my estimation to regard it as a potential wide-spread problem that needs to be specially addressed.  Consequently, I'm closing this issue.
