### ISSUE TITLE
Transcribe RADAR LEAD-IN ROUTINES (pp. 227-255)

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#77]
Transcribe the scans for the RADAR LEAD-IN ROUTINES log section into [its source file](https://github.com/rburkey2005/virtualagc/blob/master/Aurora12/RADAR_LEAD-IN_ROUTINES.agc). This section ranges from pages 227 to 255.

[Despite sharing a name with a log section in Luminary 099](https://github.com/rburkey2005/virtualagc/blob/master/Luminary099/RADAR_LEADIN_ROUTINES.agc), there appears to be no overlap between the two. (It appears that Aurora's RADAR TEST PROGRAMS became Luminary's RADAR LEADIN ROUTINES). This section will probably have to be written from scratch.

Reduced quality scans can be found [here](http://www.ibiblio.org/apollo/ScansForConversion/Aurora12/). The original quality scans are available at [the Internet Archive page for Aurora](https://archive.org/details/aurora00dapg). Note that in both cases, the page numbers specified on this ticket are those printed on the original pages, *not* those in the filenames. The numbers will be close, though, so you should be able to find them pretty quickly. The start of the log section should be fairly obvious.

**Comment by steve1780** [comment]
I'm back and I've got this one.

-Steve Case

**Comment by thewonderidiot** [comment]
Awesome, thanks!

**Comment by rburkey2005** [comment]
@steve1780 There may not have been much overlap with Luminary 099, but there's certainly some overlap with Sunburst 120, which hadn't yet been transcribed when this issue was opened up.

**Comment by 7ofNine** [comment]
I have a version of this source that assembles correctly, but I haven't adjusted the comments.
Should I complete it and submit it?
