### ISSUE TITLE
Make agc_engine() stateless?

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#802]
The vast majority of state information about the AGC is currently stored in the agc_t struct. There are, however, a few things (e.g. ScalerCounter, NextZ, the new DSKY channel 163 stuff) that are static in agc_engine.c that are used in agc_engine() that influence behavior. This has caused some grief with the NASSP team, since all of these things are lost when saving/loading scenarios, and sometimes that leads to buggy behavior.

In the past, the issue was worked around on the NASSP side by making the variables in question non-static, and saving them alongside the agc_t state structure. The better solution on both ends, I think, would be to make agc_engine() fully stateless by pushing everything agc_engine() needs to do its work into agc_t. In addition to making life easier for any future integrators of yaAGC into simulations, this would be a step in the right direction toward making #622 possible.

@rburkey2005, thoughts or objections?

**Comment by rburkey2005** [comment]
I can imagine reasons why I _could_ have done that (such as using similar machinery for yaAGC and yaAGS, but not wanting to pass yaAGC structures to yaAGC), but since I have no recollection of it, I assume it was just dumbness on my part.  So, I would endorse it.
