### ISSUE TITLE
Night Watchman should assert its channel 77 bit for 1.28 seconds

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#803]
I finally got around to integrating the channel 77 restart monitor into my FPGA builds, and the Borealis hardware alarm test turned up an interesting behavior:

![](http://i.imgur.com/hwifSYd.png)

The Night Watchman, unlike all other hardware alarms, continuously asserts its monitor output signal for a whole 1.28 seconds after a restart triggered by it occurs. This appears to have been a deliberate feature, since its input to the ALGA alarm gate (which is what causes the restarts) is very quick like all of the others. They seem to have added a whole flip-flop precisely to stretch out this signal.

agc_engine should similarly stretch out this signal, and Borealis needs to be patched to either rearrange the parity and night watchman tests or wait until the night watchman signal goes away before proceeding.

**Comment by rburkey2005** [comment]
Sounds reasonable to me.

**Comment by thewonderidiot** [comment]
This is now simulated, and the Borealis tests that I modified to pass on my hardware sim now pass on VirtualAGC too.
