### ISSUE TITLE
Transcribe SUBROUTINES (p. 887)

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#877]
Transcribe the scans for the SUBROUTINES log section into its source file. This section consists of page 887.

This section doesn't have a corresponding section in Sunburst 120, but it's only two lines long, so it should be pretty easy.

Reduced quality scans can be found [here](http://www.ibiblio.org/apollo/ScansForConversion/Sunburst37.pdf). The original quality scans are available at [the Internet Archive page for Sunburst 37/Shepatin 0](https://archive.org/details/sunburst37shepat00miti). Note that the page numbers specified on this issue correspond to those printed on the original pages, not necessarily those in the filenames of the archive.org images. Look for the start of the log section; it should be marked with a "USER'S OWN PAGE NO. 1".

**Comment by 7ofNine** [comment]
I'll take this one
