### ISSUE TITLE
Correct comments in the completed transcription

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#886]
There's two "types" of prints in Shepatin, both on the same type paper. The first half-ish is printed somewhat faintly, although not too badly, and the second half is printed nice and dark.

I've gone through all of the pages and both the print and the scan were quite good. There's only a couple of pages with random ink spatter that might cause some problems.

**Comment by rburkey2005** [comment]
Proofing with octopus/ProoferComments completed, fixed source posted, and proofing data posted as well.
