### ISSUE TITLE
EDRUPT assembles differently for BLK2

### ISSUE THREAD

**Issue by thewonderidiot** [virtualagc/virtualagc#945]
While reading through the YUL source, I came across another difference between the BLK2 and AGC targets for YUL.

>THE BLK2 ASSEMBLER REGARDS EDRUPT AS AN IMPLIED-ADDRESS EXTRACODE AND ALWAYS ASSEMBLES IT 07000.  THE AGC ASSEMBLER REGARDS IT AS A FULL EXTRACODE REQUIRING A FIXED-MEMORY ADDRESS, AND IT IS THE AGC PROGRAMMER'S RESPONSIBILITY TO SEE THAT THE ADDRESS IS BETWEEN 7000 AND 7777.

Since we don't have any examples of a BLK2 program containing EDRUPT, yaYUL always uses the AGC definition for both targets. For accuracy's sake (and forward compatibility with a potential H-1800 emulator running YUL), yaYUL should be updated to handle the difference.

Unfortunately making this change will make Borealis's extended tests containing EDRUPT invalid, so I'll have to try to convert it from BLK2 to AGC. Sigh.

**Comment by thewonderidiot** [comment]
Alright, so I've changed EDRUPT handling for --blk2, and put in workarounds for Borealis, with
```
EXTEND
EDRUPT    DOTHING
```
being replaced by the equivalent
```
OCT    6
TC     DOTHING
```

I also looked at all of the octals that changed as a result of building Borealis without --blk2, and it really does just seem to be interpreted words. So I'm going to try to transplant Sunburst 37's INTERPRETER into it and see what happens.

**Comment by thewonderidiot** [comment]
Alright, well, that went better than expected. I addressed all of the various differences that I could find. As part of pulling in INTERPRETER, I also had to update the EXECUTIVE.

Once it was all properly building again, I ran through all of the usual tests and everything still passes. So... I think the conversion worked. It's possible interpreted code is still subtly broken, since I don't use much of it often, but in theory it should work.

**Comment by rburkey2005** [comment]
I think I'm correct in believing that we have no more-extensive way (such as a mission-type context in NASSP) of running any BLK2 software.  So if whatever primitive testing of interpreter code we're capable of doesn't show any problems, then there's no reason to believe that your new changes are any worse that what was there before.

It would have been reasonable if there had originally been a test suite for the interpreter, though I don't recall ever hearing of one.
